<div class="col-md">
                    <div class="form-floating">
                        <select required class="form-select" name="analysis" id="floatingSelectGrid3" aria-label="Floating label select example">
                            <option value="Select anaylsis" selected="selected">Select anaylsis</option>
                            <option value='ASOT ( Latex) '>ASOT ( Latex) </option>
<option value='(8.21) by Fish (ES)'>(8.21) by Fish (ES)</option>
<option value='10-OH Carbazepine (CB)'>10-OH Carbazepine (CB)</option>
<option value="11 Desoxycortisol (Compound S)(CB)">11 Desoxycortisol (Compound S)(CB)
</option>
<option value='11Q by FISH (ES)'>11Q by FISH (ES)</option>
<option value='13 Q 14 by FISH (ES) '>13 Q 14 by FISH (ES) </option>
<option value='17 Alpha Hydroxyprogesterone '>17 Alpha Hydroxyprogesterone </option>
<option value='17 Hydroxy-Corticosteroids in urine (CB)'>17 Hydroxy-Corticosteroids in urine (CB)</option>
<option value='17 Ketosteroids In Urine '>17 Ketosteroids In Urine </option>
<option value='17 P by FISH '>17 P by FISH </option>
<option value='21 Hydroxylase Abs (CB)'>21 Hydroxylase Abs (CB)</option>
<option value='25(OH) Vitamin D '>25(OH) Vitamin D </option>
<option value='5 q by FISH (ES) '>5 q by FISH (ES) </option>
<option value=' 5.Nucleotidase (BG) '> 5.Nucleotidase (BG) </option>
<option value=' 5HIAA '> 5HIAA </option>
<option value=' 7 q by FISH (ES) '> 7 q by FISH (ES) </option>
<option value=' A/G Ratio '> A/G Ratio </option>
<option value=' Acetylcholine receptor antibodies. '> Acetylcholine receptor antibodies. </option>
<option value=' Acid Phosphatase (Prostatic) '> Acid Phosphatase (Prostatic) </option>
<option value=' Acid Phosphatase (Total &amp; Prostatic) '> Acid Phosphatase (Total &amp; Prostatic) </option>
<option value=' Acid Phosphatase (Total) '> Acid Phosphatase (Total) </option>
<option value=' Acidified Glycerol lysis Time(Fresh-Incubated) '> Acidified Glycerol lysis Time(Fresh-Incubated) </option>
<option value=' ACTH (am) '> ACTH (am) </option>
<option value=' ACTH (pm) '> ACTH (pm) </option>
<option value=' ACTH Stimulation Test '> ACTH Stimulation Test </option>
<option value=' ACTH Stimulation Test (Long Acting) '> ACTH Stimulation Test (Long Acting) </option>
<option value=' Actinomyces (BG) '> Actinomyces (BG) </option>
<option value=' Activated Protein C Resistance (CB) '> Activated Protein C Resistance (CB) </option>
<option value=' Adeno Virus, Serology (CB) '> Adeno Virus, Serology (CB) </option>
<option value=' Adenosine Deaminase '> Adenosine Deaminase </option>
<option value=' ADH (Antidiuretic Hormone) (CB) '> ADH (Antidiuretic Hormone) (CB) </option>
<option value=' Air Count '> Air Count </option>
<option value=' Albumin In CSF '> Albumin In CSF </option>
<option value=' Alcohol Level In Blood '> Alcohol Level In Blood </option>
<option value=' Aldosterone in urine '> Aldosterone in urine </option>
<option value=' Aldosterone. '> Aldosterone. </option>
<option value=' Alkaline Phosphatase '> Alkaline Phosphatase </option>
<option value=' Alkaline Phosphatase Isoenzymes(CB) '> Alkaline Phosphatase Isoenzymes(CB) </option>
<option value=' Alpha 2 macroglobulin '> Alpha 2 macroglobulin </option>
<option value=' Alpha Feto Protein (AFP) in serum. '> Alpha Feto Protein (AFP) in serum. </option>
<option value=' Alpha Feto Protein (AFP)in pregnancy '> Alpha Feto Protein (AFP)in pregnancy </option>
<option value=' Alpha Glucosidase In Semen '> Alpha Glucosidase In Semen </option>
<option value=' Alpha1 Anti trypsin phenotype(CB) '> Alpha1 Anti trypsin phenotype(CB) </option>
<option value=' Alpha-1 Antitrypsin in Serum '> Alpha-1 Antitrypsin in Serum </option>
<option value=' Alpha-Thalassemia Gene (BG) '> Alpha-Thalassemia Gene (BG) </option>
<option value=' Aluminum in plasma (MX) '> Aluminum in plasma (MX) </option>
<option value=' Aluminum in water (MX) '> Aluminum in water (MX) </option>
<option value=' AMA (Titre) '> AMA (Titre) </option>
<option value=' Aminogram (Plasma Quantitative) (BL) '> Aminogram (Plasma Quantitative) (BL) </option>
<option value=' Aminogram (Plasma) (ES) '> Aminogram (Plasma) (ES) </option>
<option value=' Aminogram (Urine) (ES) '> Aminogram (Urine) (ES) </option>
<option value=' Amiodarone(CB) '> Amiodarone(CB) </option>
<option value=' Amitriptyline. (CB) '> Amitriptyline. (CB) </option>
<option value=' Ammonia In Plasma '> Ammonia In Plasma </option>
<option value=' Amnicocentesis Culture (ES) '> Amnicocentesis Culture (ES) </option>
<option value=' Amniocentesis (ES) '> Amniocentesis (ES) </option>
<option value=' Amphetamine In Urine (Qualitative) '> Amphetamine In Urine (Qualitative) </option>
<option value=' Amphetamine In Urine (Quantitative). '> Amphetamine In Urine (Quantitative). </option>
<option value=' Amylase in Urine '> Amylase in Urine </option>
<option value=' Amylase, Fluid '> Amylase, Fluid </option>
<option value=' Amylase/Creat Clearance Ratio '> Amylase/Creat Clearance Ratio </option>
<option value=' Amyloid A Protein (CB) '> Amyloid A Protein (CB) </option>
<option value=' ANA Profile '> ANA Profile </option>
<option value='ANCA (Titer) '>ANCA (Titer) </option>
<option value=' ANCA-3-line '> ANCA-3-line </option>
<option value=' Androstenedione '> Androstenedione </option>
<option value='Angiotensin Converting Enzyme (ACE) '>Angiotensin Converting Enzyme (ACE) </option>
<option value=' Anion gap. '> Anion gap. </option>
<option value=' Anti '> Anti </option>
<option value=' Anti Amoeba Antibodies (IHA) (BG) '> Anti Amoeba Antibodies (IHA) (BG) </option>
<option value=' Anti Bilharzial Antibodies (IHA) '> Anti Bilharzial Antibodies (IHA) </option>
<option value=' Anti CCP Abs '> Anti CCP Abs </option>
<option value=' Anti Centromere Ab . '> Anti Centromere Ab . </option>
<option value=' Anti Desmoglein I &amp;III (CB) '> Anti Desmoglein I &amp;III (CB) </option>
<option value=' Anti DNA (Anti-ds-DNA, Anti-nat-DNA) IF '> Anti DNA (Anti-ds-DNA, Anti-nat-DNA) IF </option>
<option value=' Anti DNA (Anti-ds-DNA,) by IF (titer) '> Anti DNA (Anti-ds-DNA,) by IF (titer) </option>
<option value=' Anti DNA by ELISA '> Anti DNA by ELISA </option>
<option value=' Anti Duffy system (BB) '> Anti Duffy system (BB) </option>
<option value=' Anti Endomysium Ab (IgG&amp;IgA) '> Anti Endomysium Ab (IgG&amp;IgA) </option>
<option value=' Anti Endomysium IgA Abs '> Anti Endomysium IgA Abs </option>
<option value=' Anti Endomysium IgG Abs '> Anti Endomysium IgG Abs </option>
<option value=' Anti Factor Xa Activity (AN) '> Anti Factor Xa Activity (AN) </option>
<option value=' Anti Glomerular Basment Membrane Abs '> Anti Glomerular Basment Membrane Abs </option>
<option value=' Anti haemophilic globulin (CB) '> Anti haemophilic globulin (CB) </option>
<option value=' Anti Hu (CB) '> Anti Hu (CB) </option>
<option value=' Anti Hydatid Antibodies (IHA) '> Anti Hydatid Antibodies (IHA) </option>
<option value=' Anti intrinsic Factor antibody '> Anti intrinsic Factor antibody </option>
<option value=' Anti Islet Cells Antibodies (AN) '> Anti Islet Cells Antibodies (AN) </option>
<option value=' Anti Kell system (BB) '> Anti Kell system (BB) </option>
<option value=' Anti Keratin Abs (BG) '> Anti Keratin Abs (BG) </option>
<option value=' Anti MCV '> Anti MCV </option>
<option value=' Anti Microsomal Antibodies. '> Anti Microsomal Antibodies. </option>
<option value=' Anti Mitochondrial Antibodies (AMA) '> Anti Mitochondrial Antibodies (AMA) </option>
<option value=' Anti MNSs system (BB) '> Anti MNSs system (BB) </option>
<option value=' Anti Myelin-associated glycoprotein (BL) '> Anti Myelin-associated glycoprotein (BL) </option>
<option value=' Anti Neutrophil Cytoplasmic Ab (ANCA) '> Anti Neutrophil Cytoplasmic Ab (ANCA) </option>
<option value=' Anti Nuclear Ab Titre (ANA/Hep-2). '> Anti Nuclear Ab Titre (ANA/Hep-2). </option>
<option value=' Anti Nuclear Antibodies (ANA/Hep-2). '> Anti Nuclear Antibodies (ANA/Hep-2). </option>
<option value=' Anti Ovarian Antibodies (Anti Ovarian Ab) '> Anti Ovarian Antibodies (Anti Ovarian Ab) </option>
<option value=' Anti P1 system (BB) '> Anti P1 system (BB) </option>
<option value=' Anti Parietal Cell Antibodies (APCA) '> Anti Parietal Cell Antibodies (APCA) </option>
<option value=' Anti Proteinase 3 Abs '> Anti Proteinase 3 Abs </option>
<option value=' Anti Reticulin Abs. (CB) '> Anti Reticulin Abs. (CB) </option>
<option value=' Anti RNA '> Anti RNA </option>
<option value=' Anti RNP by ELISA. '> Anti RNP by ELISA. </option>
<option value=' Anti RNP U1 Qualitative '> Anti RNP U1 Qualitative </option>
<option value=' Anti SLA (AB) '> Anti SLA (AB) </option>
<option value=' Anti Smith Antibodies '> Anti Smith Antibodies </option>
<option value=' Anti Smooth Muscle Abs (ASMA)Titre. '> Anti Smooth Muscle Abs (ASMA)Titre. </option>
<option value=' Anti Smooth Muscle Antibodies(ASMA) '> Anti Smooth Muscle Antibodies(ASMA) </option>
<option value=' Anti SP 100 (CB) '> Anti SP 100 (CB) </option>
<option value=' Anti Sperm Antibodies (Semen). '> Anti Sperm Antibodies (Semen). </option>
<option value=' Anti Sperm Antibodies (Serum). '> Anti Sperm Antibodies (Serum). </option>
<option value=' Anti Striated Muscle Ab (CB) '> Anti Striated Muscle Ab (CB) </option>
<option value=' Anti Tissue Transglutaminase(Qualitative) '> Anti Tissue Transglutaminase(Qualitative) </option>
<option value=' Anti Tissue Transglutaminase(Quant) '> Anti Tissue Transglutaminase(Quant) </option>
<option value=' Anti Treponema Pallidum Ab '> Anti Treponema Pallidum Ab </option>
<option value=' Antibiogram for Fungi '> Antibiogram for Fungi </option>
<option value=' Antibiogram for M.tuberculosis (KA) '> Antibiogram for M.tuberculosis (KA) </option>
<option value=' Antibody screening test (BB) '> Antibody screening test (BB) </option>
<option value=' Anticardiolipin IgG '> Anticardiolipin IgG </option>
<option value=' Anticardiolipin IgM '> Anticardiolipin IgM </option>
<option value=' Anti-Mullerian Hormone. '> Anti-Mullerian Hormone. </option>
<option value=' Anti-PM1(CB) '> Anti-PM1(CB) </option>
<option value=' Antithrombin III Level '> Antithrombin III Level </option>
<option value=' Antithyroglobulin (Anti TG) Abs '> Antithyroglobulin (Anti TG) Abs </option>
<option value=' Antithyroid Antibodies (titre) '> Antithyroid Antibodies (titre) </option>
<option value=' APCA (Titre) '> APCA (Titre) </option>
<option value=' Apolipoprotein A1. '> Apolipoprotein A1. </option>
<option value=' Apolipoprotein B. '> Apolipoprotein B. </option>
<option value=' Apolipoprteins A1/ B &amp; Ratio '> Apolipoprteins A1/ B &amp; Ratio </option>
<option value=' Arsenic in Blood (MX) '> Arsenic in Blood (MX) </option>
<option value=' Arsenic in Urine (MX) '> Arsenic in Urine (MX) </option>
<option value=' Arterial Blood Gases. '> Arterial Blood Gases. </option>
<option value=' Arylsulphatase (BG) '> Arylsulphatase (BG) </option>
<option value=' Ascaris Abs (CB) '> Ascaris Abs (CB) </option>
<option value=' Ascitic Fluid Culture For AFB (T.B.) '> Ascitic Fluid Culture For AFB (T.B.) </option>
<option value=' Ascitic Fluid Culture For Fungi '> Ascitic Fluid Culture For Fungi </option>
<option value=' Ascitic Fluid Examination '> Ascitic Fluid Examination </option>
<option value=' Ascitic Fluid Examination C/S '> Ascitic Fluid Examination C/S </option>
<option value=' Ascitic Fluid Examination for Fungi '> Ascitic Fluid Examination for Fungi </option>
<option value=' Ascitic Fluid Film For AFB (T.B.) '> Ascitic Fluid Film For AFB (T.B.) </option>
<option value=' ASOT (Turbidimetric) '> ASOT (Turbidimetric) </option>
<option value=' Aspergillus Antigen in serum(CB)... '> Aspergillus Antigen in serum(CB)... </option>
<option value=' B2-Microglobulin (Serum) '> B2-Microglobulin (Serum) </option>
<option value=' B2-Microglobulin (Urine) '> B2-Microglobulin (Urine) </option>
<option value=' Bactec Blood Culture For T.B (BG) '> Bactec Blood Culture For T.B (BG) </option>
<option value=' Bactec Culture for anaerobes '> Bactec Culture for anaerobes </option>
<option value=' Bactec For T.B. (BG) '> Bactec For T.B. (BG) </option>
<option value=' Barbiturates In Urine (Qualitative) '> Barbiturates In Urine (Qualitative) </option>
<option value=' Barbiturates In Urine (Quantitative). '> Barbiturates In Urine (Quantitative). </option>
<option value=' Basal Membrane Abs (BG) '> Basal Membrane Abs (BG) </option>
<option value=' Basic myeline protein (BG) '> Basic myeline protein (BG) </option>
<option value=' Batter examination (chemical) (MX) '> Batter examination (chemical) (MX) </option>
<option value=' BCR - FISH (del.11, 12,13,17) (ES) '> BCR - FISH (del.11, 12,13,17) (ES) </option>
<option value=' BCR-ABL by FISH (ES) '> BCR-ABL by FISH (ES) </option>
<option value=' BCR-ABL by PCR '> BCR-ABL by PCR </option>
<option value=' Becker versus Duchenne for molecular diagnosis(ALL) (BL) '> Becker versus Duchenne for molecular diagnosis(ALL) (BL) </option>
<option value=' Bence Jones Protein In Urine '> Bence Jones Protein In Urine </option>
<option value=' Benzidine test for Nipple discharge '> Benzidine test for Nipple discharge </option>
<option value=' Benzodiazepine In Urine (Quantitative). '> Benzodiazepine In Urine (Quantitative). </option>
<option value=' Benzodiazepine In Urine(Qualitative) '> Benzodiazepine In Urine(Qualitative) </option>
<option value=' Berca (BG) '> Berca (BG) </option>
<option value=' Beta 2 Transferrin (CB) '> Beta 2 Transferrin (CB) </option>
<option value=' Beta Human Chorionic Gonadotropin. '> Beta Human Chorionic Gonadotropin. </option>
<option value=' Beta Hydroxy Butyrate (CB) '> Beta Hydroxy Butyrate (CB) </option>
<option value=' Beta-2-Glycoprotein Abs(IgG &amp;IgM) '> Beta-2-Glycoprotein Abs(IgG &amp;IgM) </option>
<option value=' B-HCG (Tumour Marker) '> B-HCG (Tumour Marker) </option>
<option value=' Bile Acid Total (CB) '> Bile Acid Total (CB) </option>
<option value=' Bilharzial Antigen in Urine '> Bilharzial Antigen in Urine </option>
<option value=' Bilirubin (Direct) '> Bilirubin (Direct) </option>
<option value=' Bilirubin (Total) '> Bilirubin (Total) </option>
<option value=' Biopsy (Large) '> Biopsy (Large) </option>
<option value=' Biopsy (Prost. 6 Sampls) '> Biopsy (Prost. 6 Sampls) </option>
<option value=' Biopsy (Small) '> Biopsy (Small) </option>
<option value=' Biopsy : Consultation '> Biopsy : Consultation </option>
<option value=' Biopsy : Whole Kidney '> Biopsy : Whole Kidney </option>
<option value=' Biopsy Culture for Fungi '> Biopsy Culture for Fungi </option>
<option value=' Biopsy For H. pylori(Direct Film) '> Biopsy For H. pylori(Direct Film) </option>
<option value=' Biotin -Vitamin H (BL) '> Biotin -Vitamin H (BL) </option>
<option value=' Biotinidase (BG) '> Biotinidase (BG) </option>
<option value=' Bleeding Time (IVY) '> Bleeding Time (IVY) </option>
<option value=' Blood Culture (BACTEC). '> Blood Culture (BACTEC). </option>
<option value=' Blood Culture C/S '> Blood Culture C/S </option>
<option value=' Blood Culture For Fungi '> Blood Culture For Fungi </option>
<option value=' Blood Gases, Venous '> Blood Gases, Venous </option>
<option value=' Blood Group &amp; Rh '> Blood Group &amp; Rh </option>
<option value=' Blood group Subtype (BB) '> Blood group Subtype (BB) </option>
<option value=' Blood Urea Nitrogen '> Blood Urea Nitrogen </option>
<option value=' Blood Viscosity '> Blood Viscosity </option>
<option value=' Bone Marrow : Karyotyping '> Bone Marrow : Karyotyping </option>
<option value=' Bone Marrow Aspiration '> Bone Marrow Aspiration </option>
<option value=' Bone Marrow Aspiration (Doctor Fees) '> Bone Marrow Aspiration (Doctor Fees) </option>
<option value=' Bone Marrow Doctor Fees(Biopsy) '> Bone Marrow Doctor Fees(Biopsy) </option>
<option value=' Bone Marrow Film : Consultation '> Bone Marrow Film : Consultation </option>
<option value=' Bone Marrow Immuonophenotyping '> Bone Marrow Immuonophenotyping </option>
<option value=' Bone Marrow Silver Stain '> Bone Marrow Silver Stain </option>
<option value=' Bone Marrow Trephine Biopsy '> Bone Marrow Trephine Biopsy </option>
<option value=' Bone Mrrow Aspiration&amp;Biopsy '> Bone Mrrow Aspiration&amp;Biopsy </option>
<option value=' Boron in water (MX) '> Boron in water (MX) </option>
<option value=' Borrelia Burgdorferi Abs (CB) '> Borrelia Burgdorferi Abs (CB) </option>
<option value=' Borreliosis (IgG&amp; IgM) (CB) '> Borreliosis (IgG&amp; IgM) (CB) </option>
<option value=' Brain Natriuretic Peptide (BNP)... '> Brain Natriuretic Peptide (BNP)... </option>
<option value=' Bronchial Lavage Culture For Fungi '> Bronchial Lavage Culture For Fungi </option>
<option value=' Bronchial lavage culture for T.B '> Bronchial lavage culture for T.B </option>
<option value=' Bronchial Lavage Examination '> Bronchial Lavage Examination </option>
<option value=' Bronchial Lavage Examination C/S '> Bronchial Lavage Examination C/S </option>
<option value=' Bronchial Lavage Film For AFB (T.B.) '> Bronchial Lavage Film For AFB (T.B.) </option>
<option value=' Brucella Abs CF (CB) '> Brucella Abs CF (CB) </option>
<option value=' Brucella IgM.. '> Brucella IgM.. </option>
<option value=' B-Thalassemia gene (BL) '> B-Thalassemia gene (BL) </option>
<option value=' Butterfly Fees '> Butterfly Fees </option>
<option value=' C1 Estrase Inhibitor (Activity) (CB). '> C1 Estrase Inhibitor (Activity) (CB). </option>
<option value=' C1 Estrase Inhibitor (Antigen) (CB). '> C1 Estrase Inhibitor (Antigen) (CB). </option>
<option value=' C5 - Complement Fraction (CB) '> C5 - Complement Fraction (CB) </option>
<option value=' CA 72.4 (CB) '> CA 72.4 (CB) </option>
<option value=' Cadmium (MX) '> Cadmium (MX) </option>
<option value=' Calcitonin (Thyro-Calcitonin) '> Calcitonin (Thyro-Calcitonin) </option>
<option value=' Calcium in Milk (MX) '> Calcium in Milk (MX) </option>
<option value=' Calcium In Urine/24 hrs. '> Calcium In Urine/24 hrs. </option>
<option value=' Calcium/Creatinine Ratio. '> Calcium/Creatinine Ratio. </option>
<option value=' Calprotectin In Stool (Quantitative) '> Calprotectin In Stool (Quantitative) </option>
<option value=' Campylobacter Serology (CB) '> Campylobacter Serology (CB) </option>
<option value=' cancel '> cancel </option>
<option value=' Candida Screening (CB) '> Candida Screening (CB) </option>
<option value=' Cannabinoids In Urine(Qualitative) '> Cannabinoids In Urine(Qualitative) </option>
<option value=' Cannabinoids In Urine(Quantitative). '> Cannabinoids In Urine(Quantitative). </option>
<option value=' Cannabinoids in blood Quant(CB) '> Cannabinoids in blood Quant(CB) </option>
<option value=' Capillary Fragility Test (Hess test) '> Capillary Fragility Test (Hess test) </option>
<option value=' Carbamazepin (Tegretol) Random '> Carbamazepin (Tegretol) Random </option>
<option value=' Carboxy Haemoglobin (CB) '> Carboxy Haemoglobin (CB) </option>
<option value=' Carcinoembryonic Antigen (CEA) '> Carcinoembryonic Antigen (CEA) </option>
<option value=' Carnitine in plasma (CB) '> Carnitine in plasma (CB) </option>
<option value=' CASA (computerized semen analysis ) '> CASA (computerized semen analysis ) </option>
<option value=' Catecholamines in blood '> Catecholamines in blood </option>
<option value=' Catecholamines in Urine. '> Catecholamines in Urine. </option>
<option value=' CD Markers '> CD Markers </option>
<option value=' CD11c (TH) '> CD11c (TH) </option>
<option value=' CD31 '> CD31 </option>
<option value=' CD4 / CD 8 ratio '> CD4 / CD 8 ratio </option>
<option value=' Certican (Everolimus ) '> Certican (Everolimus ) </option>
<option value=' Ceruloplasmin Level '> Ceruloplasmin Level </option>
<option value=' Cervical Film For AFB (T.B.) '> Cervical Film For AFB (T.B.) </option>
<option value=' Cervical Antisperms Ab (Total) '> Cervical Antisperms Ab (Total) </option>
<option value=' Cervical Culture For Fungi '> Cervical Culture For Fungi </option>
<option value=' Cervical Disch. Culture For AFB (T.B.) '> Cervical Disch. Culture For AFB (T.B.) </option>
<option value=' Cervical Discharge Exam. &amp; C/S '> Cervical Discharge Exam. &amp; C/S </option>
<option value=' CH 50 (AN) '> CH 50 (AN) </option>
<option value=' Chest Allergy(ALFA PNEUMO- CARE) '> Chest Allergy(ALFA PNEUMO- CARE) </option>
<option value=' Chlamydia Antibodies (IgA) (CB) '> Chlamydia Antibodies (IgA) (CB) </option>
<option value=' Chlamydia Antibodies (IgG) '> Chlamydia Antibodies (IgG) </option>
<option value=' Chlamydia Antigen '> Chlamydia Antigen </option>
<option value=' Chlamydia Pneumonia by PCR (CB) '> Chlamydia Pneumonia by PCR (CB) </option>
<option value=' Chlamydia Pneumoniae Ab (CB) '> Chlamydia Pneumoniae Ab (CB) </option>
<option value=' Chloride In Serum '> Chloride In Serum </option>
<option value=' Chol./HDL/LDL/Triglycer./Apo A1/Apo B. '> Chol./HDL/LDL/Triglycer./Apo A1/Apo B. </option>
<option value=' Cholest./HDL/LDL/Triglycerides. '> Cholest./HDL/LDL/Triglycerides. </option>
<option value=' Cholinesterases(CB) '> Cholinesterases(CB) </option>
<option value=' Chromium (CB) '> Chromium (CB) </option>
<option value=' Chromium (Urine) (CB) '> Chromium (Urine) (CB) </option>
<option value=' Chromogranin A (CB) '> Chromogranin A (CB) </option>
<option value=' Chromosomal Study '> Chromosomal Study </option>
<option value=' Chromosomal Study In Bone Marrow '> Chromosomal Study In Bone Marrow </option>
<option value=' Circulating Immunocomplex (CB) '> Circulating Immunocomplex (CB) </option>
<option value=' Citrate in urine '> Citrate in urine </option>
<option value=' CK (Total) '> CK (Total) </option>
<option value=' CK Isoenzymes (CB) '> CK Isoenzymes (CB) </option>
<option value=' CK-MB '> CK-MB </option>
<option value=' CK-MB (Mass)..... '> CK-MB (Mass)..... </option>
<option value=' Clostridium Difficile toxins(A&amp;B)in faeces '> Clostridium Difficile toxins(A&amp;B)in faeces </option>
<option value=' Clot Lysis : Whole Blood '> Clot Lysis : Whole Blood </option>
<option value=' Clot Retraction test '> Clot Retraction test </option>
<option value=' Clotting Time (Lee-White) '> Clotting Time (Lee-White) </option>
<option value=' Clozapine (CB) '> Clozapine (CB) </option>
<option value=' CMV Antibodies (IgG) '> CMV Antibodies (IgG) </option>
<option value=' CMV Antibodies (IgM) '> CMV Antibodies (IgM) </option>
<option value=' CMV by PCR (Quantitative) '> CMV by PCR (Quantitative) </option>
<option value=' CMV by PCR in CSF (AN) '> CMV by PCR in CSF (AN) </option>
<option value=' CMV IgG Avidity Test (CB) '> CMV IgG Avidity Test (CB) </option>
<option value=' Cocaine In Urine (Qualitative) '> Cocaine In Urine (Qualitative) </option>
<option value=' Cocaine In Urine (Quantitative). '> Cocaine In Urine (Quantitative). </option>
<option value=' Coenzyme Q10 (CB) '> Coenzyme Q10 (CB) </option>
<option value=' Coffee (Bacteriological examination ) '> Coffee (Bacteriological examination ) </option>
<option value=' Coffee (Chemical examination) (MX) '> Coffee (Chemical examination) (MX) </option>
<option value=' Cold Agglutinin. '> Cold Agglutinin. </option>
<option value=' Complement C2 in Serum (CB) '> Complement C2 in Serum (CB) </option>
<option value=' Complement C3 in Serum '> Complement C3 in Serum </option>
<option value=' Complement C4 in Serum '> Complement C4 in Serum </option>
<option value=' Complement Component C2 (CB) '> Complement Component C2 (CB) </option>
<option value=' Complete Blood Picture (CBC) '> Complete Blood Picture (CBC) </option>
<option value=' Complment level C1Q (CB) '> Complment level C1Q (CB) </option>
<option value=' Conjunctival Culture For Fungi '> Conjunctival Culture For Fungi </option>
<option value=' Conjunctival Disch. Exam. C/S (Left) '> Conjunctival Disch. Exam. C/S (Left) </option>
<option value=' Conjunctival Disch. Exam. C/S (Right) '> Conjunctival Disch. Exam. C/S (Right) </option>
<option value=' Copper In Blood '> Copper In Blood </option>
<option value=' Copper in Hair (MX) '> Copper in Hair (MX) </option>
<option value=' Copper in Milk (MX) '> Copper in Milk (MX) </option>
<option value=' Copper In Urine '> Copper In Urine </option>
<option value=' Corticosterone (CB) '> Corticosterone (CB) </option>
<option value=' Cortisol In Urine '> Cortisol In Urine </option>
<option value=' Coxasack B1 - B6 (IgM) (BL) '> Coxasack B1 - B6 (IgM) (BL) </option>
<option value=' Coxasackie B1- B6 IgG (BL) '> Coxasackie B1- B6 IgG (BL) </option>
<option value=' Coxiella Burnetii (Q fever) (BL) '> Coxiella Burnetii (Q fever) (BL) </option>
<option value=' C-Peptide (fasting) '> C-Peptide (fasting) </option>
<option value=' C-Peptide (postprandial) '> C-Peptide (postprandial) </option>
<option value=' C-Peptide in urine '> C-Peptide in urine </option>
<option value=' C-Reactive Protein (CRP) Titre '> C-Reactive Protein (CRP) Titre </option>
<option value=' Creatine In Urine (CB) '> Creatine In Urine (CB) </option>
<option value=' Creatinine Clearance '> Creatinine Clearance </option>
<option value=' Creatinine in Urine Random '> Creatinine in Urine Random </option>
<option value=' Creatinine Level in 24hr Urine '> Creatinine Level in 24hr Urine </option>
<option value=' Cross Matching (Blood) (AN) '> Cross Matching (Blood) (AN) </option>
<option value=' CRP Ultrasensitive '> CRP Ultrasensitive </option>
<option value=' Cryoglobulins '> Cryoglobulins </option>
<option value=' Cryptococcus Antigen (CB) '> Cryptococcus Antigen (CB) </option>
<option value=' Cryptosporidia In Stool (direct ex) '> Cryptosporidia In Stool (direct ex) </option>
<option value=' CSF Culture For AFB (T.B.) '> CSF Culture For AFB (T.B.) </option>
<option value=' CSF Culture For Fungi '> CSF Culture For Fungi </option>
<option value=' CSF Examination '> CSF Examination </option>
<option value=' CSF Examination C/S '> CSF Examination C/S </option>
<option value=' CSF Film For AFB (T.B.) '> CSF Film For AFB (T.B.) </option>
<option value=' Culture for Anaerobes C/S '> Culture for Anaerobes C/S </option>
<option value=' Culture for Campylo bacter spp '> Culture for Campylo bacter spp </option>
<option value=' Culture For T.B '> Culture For T.B </option>
<option value=' CVD Strip Assay '> CVD Strip Assay </option>
<option value=' Cyclic AMP in urine (CB) '> Cyclic AMP in urine (CB) </option>
<option value=' Cyclosporine Level(Peak). '> Cyclosporine Level(Peak). </option>
<option value=' Cyclosporine Level(Trough) '> Cyclosporine Level(Trough) </option>
<option value=' Cystatin C (CB) '> Cystatin C (CB) </option>
<option value=' Cystic Fibrosis by PCR '> Cystic Fibrosis by PCR </option>
<option value=' Cystic Fluid Exam &amp; Culture '> Cystic Fluid Exam &amp; Culture </option>
<option value=' Cystic Fluid Examination '> Cystic Fluid Examination </option>
<option value=' Cysticercosis Serology (CB) '> Cysticercosis Serology (CB) </option>
<option value=' Cystine Level in Urine (Quant) (CB) '> Cystine Level in Urine (Quant) (CB) </option>
<option value=' Cytochem, Leucocyte : Chlorac Est. '> Cytochem, Leucocyte : Chlorac Est. </option>
<option value=' Cytochem, Leucocyte : NASA '> Cytochem, Leucocyte : NASA </option>
<option value=' Cytochem, Leucocyte : NASA - F '> Cytochem, Leucocyte : NASA - F </option>
<option value=' Cytochem, Leucocyte : PAS '> Cytochem, Leucocyte : PAS </option>
<option value=' Cytochem, Leucocyte : Peroxidase '> Cytochem, Leucocyte : Peroxidase </option>
<option value=' Cytochem, Leucocyte : Sudan Black '> Cytochem, Leucocyte : Sudan Black </option>
<option value=' Cytochem,Non-specific Estrase '> Cytochem,Non-specific Estrase </option>
<option value=' Cytochemistry : Acid Phosphatase '> Cytochemistry : Acid Phosphatase </option>
<option value=' Cytochemistry : Acid Phosphatase (Tart) '> Cytochemistry : Acid Phosphatase (Tart) </option>
<option value=' Cytochemistry : Leuc Alk. Ph. (LAP) '> Cytochemistry : Leuc Alk. Ph. (LAP) </option>
<option value=' Cytokeratin '> Cytokeratin </option>
<option value=' Cytology : Consultation '> Cytology : Consultation </option>
<option value=' Cytology. '> Cytology. </option>
<option value=' Cytotoxic Antibodies (BL)'> Cytotoxic Antibodies (BL)</option>
<option value=' D-Dimer.'> D-Dimer.</option>
<option value=' Delta Amino lovevulinic acid (CB) '> Delta Amino lovevulinic acid (CB) </option>
<option value=' Dengue virus IgM (CB) '> Dengue virus IgM (CB) </option>
<option value=' Depakine (Valproic acid), Peak '> Depakine (Valproic acid), Peak </option>
<option value=' Depakine (Valproic acid), Trough '> Depakine (Valproic acid), Trough </option>
<option value=' Dexamethasone Suppression Test '> Dexamethasone Suppression Test </option>
<option value=' Diazepam Structure (Valium) (CB) '> Diazepam Structure (Valium) (CB) </option>
<option value=' Digoxin (Lanoxin) '> Digoxin (Lanoxin) </option>
<option value=' Dihydro hodamine (DHR) (TH) '> Dihydro hodamine (DHR) (TH) </option>
<option value=' Dihydrotestosterone (DHT ) (CB) '> Dihydrotestosterone (DHT ) (CB) </option>
<option value=' Diphtheria Abs. (CB) '> Diphtheria Abs. (CB) </option>
<option value=' Direct Coomb^s Test '> Direct Coomb^s Test </option>
<option value=' Dissolved Oxygen (mx) '> Dissolved Oxygen (mx) </option>
<option value=' DNA extraction '> DNA extraction </option>
<option value=' DNA Paternity Test (ES) '> DNA Paternity Test (ES) </option>
<option value=' Doctor Fees '> Doctor Fees </option>
<option value=' Doctor Fees (Food) '> Doctor Fees (Food) </option>
<option value=' Doctor Fees for semen processing '> Doctor Fees for semen processing </option>
<option value=' Double Marker Test (SN) '> Double Marker Test (SN) </option>
<option value=' Drugs of Abuse (Qualitative) '> Drugs of Abuse (Qualitative) </option>
<option value=' Ear Culture For Fungi '> Ear Culture For Fungi </option>
<option value=' Ear Discharge Exam. C/S (Left) '> Ear Discharge Exam. C/S (Left) </option>
<option value=' Ear Discharge Exam. C/S (Right) '> Ear Discharge Exam. C/S (Right) </option>
<option value=' EBV by PCR (AN) '> EBV by PCR (AN) </option>
<option value=' EBV by PCR in CSF (AN) '> EBV by PCR in CSF (AN) </option>
<option value=' EBV-EA (IgG) (SN) '> EBV-EA (IgG) (SN) </option>
<option value=' EBV-EA (IgM) (SN) '> EBV-EA (IgM) (SN) </option>
<option value=' EBV-EBNA (IgG)-ELISA '> EBV-EBNA (IgG)-ELISA </option>
<option value=' EBV-VCA (IgM) '> EBV-VCA (IgM) </option>
<option value=' EBV-VCA-(IgG) '> EBV-VCA-(IgG) </option>
<option value=' Elastase Feces '> Elastase Feces </option>
<option value=' Eosinophil Smear : Conjunctiva '> Eosinophil Smear : Conjunctiva </option>
<option value=' Eosinophil Smear: Nasal Secretion '> Eosinophil Smear: Nasal Secretion </option>
<option value=' Eosinophil Smear: Sputum '> Eosinophil Smear: Sputum </option>
<option value=' Eosinophils in urine........ '> Eosinophils in urine........ </option>
<option value=' Erythrocyte Sedimentation Rate (E.S.R) '> Erythrocyte Sedimentation Rate (E.S.R) </option>
<option value=' Erythropoietin (CB) '> Erythropoietin (CB) </option>
<option value=' Estimated Glomerular Filtration Rate '> Estimated Glomerular Filtration Rate </option>
<option value=' Estradiol (E2) '> Estradiol (E2) </option>
<option value=' Estriol (E3), Free '> Estriol (E3), Free </option>
<option value=' Estrogen Receptors (Breast) '> Estrogen Receptors (Breast) </option>
<option value=' Estron E1 (CB) '> Estron E1 (CB) </option>
<option value=' Factor IX '> Factor IX </option>
<option value=' Factor V '> Factor V </option>
<option value=' Factor V Leiden &amp; Proth. 20210 &amp; MTHFR '> Factor V Leiden &amp; Proth. 20210 &amp; MTHFR </option>
<option value=' Factor V Leiden &amp; Prothrombin 20210 '> Factor V Leiden &amp; Prothrombin 20210 </option>
<option value=' Factor V Leiden G1691A mutation '> Factor V Leiden G1691A mutation </option>
<option value=' Factor VII '> Factor VII </option>
<option value=' Factor VIII '> Factor VIII </option>
<option value=' Factor X '> Factor X </option>
<option value=' Factor XI (CB) '> Factor XI (CB) </option>
<option value=' Factor XII (Hageman Factor) (CB) '> Factor XII (Hageman Factor) (CB) </option>
<option value=' FactorXIII (CB) '> FactorXIII (CB) </option>
<option value=' Familial Mediterranean Fever Gene '> Familial Mediterranean Fever Gene </option>
<option value=' Fanconi anemia chromosomal breakage '> Fanconi anemia chromosomal breakage </option>
<option value=' Fasciola Antibodies (AN) '> Fasciola Antibodies (AN) </option>
<option value=' Fasting Plasma Glucose '> Fasting Plasma Glucose </option>
<option value=' Ferritin in Serum '> Ferritin in Serum </option>
<option value=' Fetus (Biopsy) '> Fetus (Biopsy) </option>
<option value=' Fibrinogen Degradation Products (FDPs) '> Fibrinogen Degradation Products (FDPs) </option>
<option value=' Fibrinogen Level (Titre) '> Fibrinogen Level (Titre) </option>
<option value=' FibroMax '> FibroMax </option>
<option value=' Fibrotest and Actitest '> Fibrotest and Actitest </option>
<option value=' Filariasis - Serology (CB) '> Filariasis - Serology (CB) </option>
<option value=' Film For Malaria '> Film For Malaria </option>
<option value='FIP1L1 PDGFRa (ES) '>FIP1L1 PDGFRa (ES) </option>
<option value='FIP1L1 PDGFRb (ES) '>FIP1L1 PDGFRb (ES) </option>
<option value='Fluoride in serum (CB) '>Fluoride in serum (CB) </option>
<option value='FMC7. (SN) '>FMC7. (SN) </option>
<option value='FNAC '>FNAC </option>
<option value='FNAC (Doctor Fees) '>FNAC (Doctor Fees) </option>
<option value='Folic acid In RBCs (BG) '>Folic acid In RBCs (BG) </option>
<option value='Folic Acid in serum... '>Folic Acid in serum... </option>
<option value='Food (بيتزا) '>Food (بيتزا) </option>
<option value='Food (مخبوزات). '>Food (مخبوزات). </option>
<option value='Food Chemical ex مكرونه '>Food Chemical ex مكرونه </option>
<option value='Food Contact Surface Swab...... '>Food Contact Surface Swab...... </option>
<option value='Food Examination '>Food Examination </option>
<option value='Food Microbiological Examination(Sample Collection.. '>Food Microbiological Examination(Sample Collection.. </option>
<option value='Food الارز '>Food الارز </option>
<option value='Food البسطرمه '>Food البسطرمه </option>
<option value='Food الجبن الامنتال '>Food الجبن الامنتال </option>
<option value='Food الجبن الايدام '>Food الجبن الايدام </option>
<option value='Food الجبن الجوداـنصف جاف '>Food الجبن الجوداـنصف جاف </option>
<option value='Food الجبن الشيدر '>Food الجبن الشيدر </option>
<option value='Food الحبوب '>Food الحبوب </option>
<option value='Food الحلاوه الطحينيه '>Food الحلاوه الطحينيه </option>
<option value='Food الدقيق '>Food الدقيق </option>
<option value='Food الدواجن المجمده '>Food الدواجن المجمده </option>
<option value='Food السبيط '>Food السبيط </option>
<option value='Food الشطه '>Food الشطه </option>
<option value='Food الطحينه '>Food الطحينه </option>
<option value='Food الفستق '>Food الفستق </option>
<option value='Food القرفه '>Food القرفه </option>
<option value='Food القلقاس المجمد '>Food القلقاس المجمد </option>
<option value='Food الكاكاو-الشيكولاته '>Food الكاكاو-الشيكولاته </option>
<option value='Food الكاندبيف '>Food الكاندبيف </option>
<option value='Food الكركم '>Food الكركم </option>
<option value='Food الكمون '>Food الكمون </option>
<option value='Food اللانشون(المعلب المطهي-نصف الجاف) '>Food اللانشون(المعلب المطهي-نصف الجاف) </option>
<option value='Food اللبن المعقم طويل المدي '>Food اللبن المعقم طويل المدي </option>
<option value='Food اللحم المفروم '>Food اللحم المفروم </option>
<option value='Food اللحوم المبرده '>Food اللحوم المبرده </option>
<option value='Food اللحوم ومنتجاتها(السلامي) '>Food اللحوم ومنتجاتها(السلامي) </option>
<option value='food المخللات المعباه '>food المخللات المعباه </option>
<option value='Food المشروم '>Food المشروم </option>
<option value='Food برجر لحم مجمد '>Food برجر لحم مجمد </option>
<option value='food صلصه توابل بالطاطم(الكاتشاب) '>food صلصه توابل بالطاطم(الكاتشاب) </option>
<option value='Food عين الجمل '>Food عين الجمل </option>
<option value='Food فرانكفورتر-هوت دوج-سوسيس '>Food فرانكفورتر-هوت دوج-سوسيس </option>
<option value='Food مايونيز '>Food مايونيز </option>
<option value='Food(اسماك وجمبري). '>Food(اسماك وجمبري). </option>
<option value='Food(الجبنه القشطه). '>Food(الجبنه القشطه). </option>
<option value='Food(السجق اللحوم المصنعه). '>Food(السجق اللحوم المصنعه). </option>
<option value='Food(السلطه). '>Food(السلطه). </option>
<option value='Food(الطيور). '>Food(الطيور). </option>
<option value='Food(العصير). '>Food(العصير). </option>
<option value='Food(الكفته المفروم)....... '>Food(الكفته المفروم)....... </option>
<option value='Food(المياه). '>Food(المياه). </option>
<option value='Food(كباب حله). '>Food(كباب حله). </option>
<option value='Formaline detection in cheese (MX) '>Formaline detection in cheese (MX) </option>
<option value='Fractional Excretion of Sodium. '>Fractional Excretion of Sodium. </option>
<option value='Fragile X Molecular Study (PCR) (CB) '>Fragile X Molecular Study (PCR) (CB) </option>
<option value='Free carbon dioxide (mx) '>Free carbon dioxide (mx) </option>
<option value='Free Fatty Acid (CB) '>Free Fatty Acid (CB) </option>
<option value='Free light chain in Serum (BG) '>Free light chain in Serum (BG) </option>
<option value='Free T3 '>Free T3 </option>
<option value='Free T4 '>Free T4 </option>
<option value='Free Testosterone '>Free Testosterone </option>
<option value='Free Testosterone and Index '>Free Testosterone and Index </option>
<option value='Free Thyroxine Index (FTI) '>Free Thyroxine Index (FTI) </option>
<option value='Frozen Section '>Frozen Section </option>
<option value='Fructosamine (Serum) '>Fructosamine (Serum) </option>
<option value='Fructose in blood (AN) '>Fructose in blood (AN) </option>
<option value='Fructose in Semen '>Fructose in Semen </option>
<option value='FSH '>FSH </option>
<option value='G6PD Activity (Qualitative) '>G6PD Activity (Qualitative) </option>
<option value='G6PD Activity (Quantitative) '>G6PD Activity (Quantitative) </option>
<option value='Galactosaemia Screen(sn) (GL) '>Galactosaemia Screen(sn) (GL) </option>
<option value='Galactose-1-P uridyltransferase (BL) '>Galactose-1-P uridyltransferase (BL) </option>
<option value='Gamma GT (GGT) '>Gamma GT (GGT) </option>
<option value='Gastrin Level (CB) '>Gastrin Level (CB) </option>
<option value='Gastro-5-line. '>Gastro-5-line. </option>
<option value='Genetic Councelling '>Genetic Councelling </option>
<option value='Glucose Curve for Pregnants(3sample) '>Glucose Curve for Pregnants(3sample) </option>
<option value='Glucose Curve for Pregnants(4sample) '>Glucose Curve for Pregnants(4sample) </option>
<option value='Glucose In Urine '>Glucose In Urine </option>
<option value='Glucose Tolerance Test (3 samples) '>Glucose Tolerance Test (3 samples) </option>
<option value='Glucose Tolerance Test (5 Samples) '>Glucose Tolerance Test (5 Samples) </option>
<option value='Glutamate Decarboxylase ABS (CB) '>Glutamate Decarboxylase ABS (CB) </option>
<option value='Glutathione (CB) '>Glutathione (CB) </option>
<option value='Glycated Serum Protein. '>Glycated Serum Protein. </option>
<option value='Glycerol Lysis Test . '>Glycerol Lysis Test . </option>
<option value='Glycine in CSF '>Glycine in CSF </option>
<option value='Glycosylated Haemoglobin (HbA1c) '>Glycosylated Haemoglobin (HbA1c) </option>
<option value='Gonorrhea by Gram stain '>Gonorrhea by Gram stain </option>
<option value='Growth Hormone '>Growth Hormone </option>
<option value='Growth Hormone Clonidine-Stimul. Test '>Growth Hormone Clonidine-Stimul. Test </option>
<option value='Growth Hormone Glucose-Suppr. Test (3) '>Growth Hormone Glucose-Suppr. Test (3) </option>
<option value='Growth Hormone Glucose-Suppr. Test (5) '>Growth Hormone Glucose-Suppr. Test (5) </option>
<option value='Growth Hormone Insulin-Stimulation Test '>Growth Hormone Insulin-Stimulation Test </option>
<option value='H. pylori (Urea Breath Test) '>H. pylori (Urea Breath Test) </option>
<option value='H. pylori Abs (IgA).. '>H. pylori Abs (IgA).. </option>
<option value='H. pylori Abs:IgG, IgA '>H. pylori Abs:IgG, IgA </option>
<option value='H. pylori Ag In Stool. '>H. pylori Ag In Stool. </option>
<option value='H. pylori IgG Abs (Qualitative) '>H. pylori IgG Abs (Qualitative) </option>
<option value='H. pylori IgG Abs (Quantitative). '>H. pylori IgG Abs (Quantitative). </option>
<option value='H. pylori IgM (Quantitative) '>H. pylori IgM (Quantitative) </option>
<option value='H. pylori Line Test '>H. pylori Line Test </option>
<option value='H1N1 (Swine Flu) PCR '>H1N1 (Swine Flu) PCR </option>
<option value='Haematocrit '>Haematocrit </option>
<option value='Haemoglobin Electrophoresis. '>Haemoglobin Electrophoresis. </option>
<option value='Haemoglobin Level '>Haemoglobin Level </option>
<option value='Haemopexin (CB) '>Haemopexin (CB) </option>
<option value='Haemophilus Influenzae B:IgG ABS (CB) '>Haemophilus Influenzae B:IgG ABS (CB) </option>
<option value='Haemosiderin (BL) '>Haemosiderin (BL) </option>
<option value='Hair culture for fungi '>Hair culture for fungi </option>
<option value='Hair Examination for fungi '>Hair Examination for fungi </option>
<option value='Ham^s Test '>Ham^s Test </option>
<option value='Haptoglobin Level '>Haptoglobin Level </option>
<option value='HAV antibodies - IgM '>HAV antibodies - IgM </option>
<option value='HAV antibody - IgG '>HAV antibody - IgG </option>
<option value='Hb Variant by HPLC '>Hb Variant by HPLC </option>
<option value='HBc Antibodies IgM '>HBc Antibodies IgM </option>
<option value='HBc Antibodies Total '>HBc Antibodies Total </option>
<option value='HBe Antibody '>HBe Antibody </option>
<option value='HBe Antigen '>HBe Antigen </option>
<option value='HBs Ab '>HBs Ab </option>
<option value='HBs Antigen '>HBs Antigen </option>
<option value='HBV DNA by PCR (Qualitative) '>HBV DNA by PCR (Qualitative) </option>
<option value='HBV DNA by PCR (Quantitative) '>HBV DNA by PCR (Quantitative) </option>
<option value='HCV Genotyping (AN) '>HCV Genotyping (AN) </option>
<option value='HCV Antibody 3rd Generation '>HCV Antibody 3rd Generation </option>
<option value='HCV IgM '>HCV IgM </option>
<option value='HCV RNA (Quantitative) '>HCV RNA (Quantitative) </option>
<option value='HCV RNA by PCR (Qualitative) '>HCV RNA by PCR (Qualitative) </option>
<option value='HDL-Cholesterol '>HDL-Cholesterol </option>
<option value='HDV Antibodies IgM (CB) '>HDV Antibodies IgM (CB) </option>
<option value='HDV Antigen (CB) '>HDV Antigen (CB) </option>
<option value='Heavy Metals In Water. (MX) '>Heavy Metals In Water. (MX) </option>
<option value='Heinz Body Stain '>Heinz Body Stain </option>
<option value='Hemochromatosis Gene (CB) '>Hemochromatosis Gene (CB) </option>
<option value='Hemochromatosis gene(p.His63Asp) (BL) '>Hemochromatosis gene(p.His63Asp) (BL) </option>
<option value='Her - 2 '>Her - 2 </option>
<option value='Herpes Simplex Virus by PCR (1&amp;2) (CB) '>Herpes Simplex Virus by PCR (1&amp;2) (CB) </option>
<option value='Herpes Virus Type 6 DNA (CB) '>Herpes Virus Type 6 DNA (CB) </option>
<option value='HEV Abs (IgG - IgM) (CB) '>HEV Abs (IgG - IgM) (CB) </option>
<option value='HEV IgG (CB) '>HEV IgG (CB) </option>
<option value='HEV IgM (CB) '>HEV IgM (CB) </option>
<option value='Histamine, Plasma (CB) '>Histamine, Plasma (CB) </option>
<option value='HIV 1 &amp; 2 antibodies (AIDS test) '>HIV 1 &amp; 2 antibodies (AIDS test) </option>
<option value='HIV by PCR (Quantitative) (BL) '>HIV by PCR (Quantitative) (BL) </option>
<option value='HIV I ANTIGEN (P24) (CB) '>HIV I ANTIGEN (P24) (CB) </option>
<option value='HLA B27 '>HLA B27 </option>
<option value='HLA B5 '>HLA B5 </option>
<option value='HLA Class DQ (DQ2 - DQ 8) (BG) '>HLA Class DQ (DQ2 - DQ 8) (BG) </option>
<option value='HLA Class I - A by PCR '>HLA Class I - A by PCR </option>
<option value='HLA Class I - B by PCR '>HLA Class I - B by PCR </option>
<option value='HLA Class I (A&amp;B) by PCR '>HLA Class I (A&amp;B) by PCR </option>
<option value='HLA Final Cross Matching (AN) '>HLA Final Cross Matching (AN) </option>
<option value='HLA Typing Class II (DR) by PCR '>HLA Typing Class II (DR) by PCR </option>
<option value='HOMA Test. '>HOMA Test. </option>
<option value='Homocysteine '>Homocysteine </option>
<option value='Homocysteine in Urine (CB) '>Homocysteine in Urine (CB) </option>
<option value='House call1 '>House call1 </option>
<option value='House call2 '>House call2 </option>
<option value='HPLC for Hb Variants '>HPLC for Hb Variants </option>
<option value='HSV - 1 IgG '>HSV - 1 IgG </option>
<option value='HSV - 1 IgM '>HSV - 1 IgM </option>
<option value='HSV - 2 IgG '>HSV - 2 IgG </option>
<option value='HSV- 2 IgM '>HSV- 2 IgM </option>
<option value='HTLV 1/2 Screening Serology (CB) RRRR '>HTLV 1/2 Screening Serology (CB) RRRR </option>
<option value='Human Corona virus 2012 (MERS) '>Human Corona virus 2012 (MERS) </option>
<option value='Hyaluronic Acid (CB) '>Hyaluronic Acid (CB) </option>
<option value='Hydroxyproline In Urine (CB) '>Hydroxyproline In Urine (CB) </option>
<option value='IA2 Antibodies (CB) '>IA2 Antibodies (CB) </option>
<option value='IgA Level (Serum) '>IgA Level (Serum) </option>
<option value='IgE Level (Total) '>IgE Level (Total) </option>
<option value='IgE Specific (Food Allergens) '>IgE Specific (Food Allergens) </option>
<option value='IgE Specific (Inhalants). '>IgE Specific (Inhalants). </option>
<option value='IgG In CSF (AN) '>IgG In CSF (AN) </option>
<option value='IgG In Urine (CB) '>IgG In Urine (CB) </option>
<option value='IgG Level (Serum) '>IgG Level (Serum) </option>
<option value='IgG Subclass 1 (CB) '>IgG Subclass 1 (CB) </option>
<option value='IgG Subclass 2 (CB) '>IgG Subclass 2 (CB) </option>
<option value='IgG Subclass 3 (CB) '>IgG Subclass 3 (CB) </option>
<option value='IgG Subclass 4 (CB) '>IgG Subclass 4 (CB) </option>
<option value='IgM Level (Serum) '>IgM Level (Serum) </option>
<option value='Immunofixation in Urine (AN) '>Immunofixation in Urine (AN) </option>
<option value='Immunoglobulin D (CB) '>Immunoglobulin D (CB) </option>
<option value='Immunohistochemistry (Biopsy) 4stains '>Immunohistochemistry (Biopsy) 4stains </option>
<option value='Immunohistochemistry (One stain) '>Immunohistochemistry (One stain) </option>
<option value='Immunophenotyping '>Immunophenotyping </option>
<option value='Immunophenotyping : CD (glycophorin A) '>Immunophenotyping : CD (glycophorin A) </option>
<option value='Immunophenotyping : CD (HLA-DR) '>Immunophenotyping : CD (HLA-DR) </option>
<option value='Immunophenotyping : CD (MPO) '>Immunophenotyping : CD (MPO) </option>
<option value='Immunophenotyping : CD 25 '>Immunophenotyping : CD 25 </option>
<option value='Immunophenotyping : CD103 '>Immunophenotyping : CD103 </option>
<option value='Immunophenotyping : CD23 '>Immunophenotyping : CD23 </option>
<option value='Immunophenotyping : CD45 '>Immunophenotyping : CD45 </option>
<option value='Immunophenotyping ; CD Tdt '>Immunophenotyping ; CD Tdt </option>
<option value='Immunophenotyping : CD (kappa) '>Immunophenotyping : CD (kappa) </option>
<option value='Immunophenotyping : CD 30 '>Immunophenotyping : CD 30 </option>
<option value='Immunophenotyping : CD1 '>Immunophenotyping : CD1 </option>
<option value='Immunophenotyping : CD10 '>Immunophenotyping : CD10 </option>
<option value='Immunophenotyping : CD13 '>Immunophenotyping : CD13 </option>
<option value='Immunophenotyping : CD15 '>Immunophenotyping : CD15 </option>
<option value='Immunophenotyping : CD19 '>Immunophenotyping : CD19 </option>
<option value='Immunophenotyping : CD2 '>Immunophenotyping : CD2 </option>
<option value='Immunophenotyping : CD20 '>Immunophenotyping : CD20 </option>
<option value='Immunophenotyping : CD3 '>Immunophenotyping : CD3 </option>
<option value='Immunophenotyping : CD4 '>Immunophenotyping : CD4 </option>
<option value='Immunophenotyping : CD41 '>Immunophenotyping : CD41 </option>
<option value='Immunophenotyping : CD5 '>Immunophenotyping : CD5 </option>
<option value='Immunophenotyping : CD56 (NK) '>Immunophenotyping : CD56 (NK) </option>
<option value='Immunophenotyping : CD57 '>Immunophenotyping : CD57 </option>
<option value='Immunophenotyping : CD7 '>Immunophenotyping : CD7 </option>
<option value='Immunophenotyping : CD79a '>Immunophenotyping : CD79a </option>
<option value='Immunophenotyping : CD8 '>Immunophenotyping : CD8 </option>
<option value='Immunophenotyping :CD 138 '>Immunophenotyping :CD 138 </option>
<option value='Immunophenotyping :CD 21 '>Immunophenotyping :CD 21 </option>
<option value='Immunophenotyping CD38. '>Immunophenotyping CD38. </option>
<option value='Immunophenotyping: CD14 '>Immunophenotyping: CD14 </option>
<option value='Immunophenotyping: CD16 (NK) '>Immunophenotyping: CD16 (NK) </option>
<option value='Immunophenotyping: CD22 '>Immunophenotyping: CD22 </option>
<option value='Immunophenotyping: CD33.. '>Immunophenotyping: CD33.. </option>
<option value='Immunophenotyping: CD34... '>Immunophenotyping: CD34... </option>
<option value='Immunophenotyping: CD55..... '>Immunophenotyping: CD55..... </option>
<option value='Immunophenotyping: CD59... '>Immunophenotyping: CD59... </option>
<option value='Immunophenotyping: CD79b '>Immunophenotyping: CD79b </option>
<option value='Indirect Bilirubin , Serum '>Indirect Bilirubin , Serum </option>
<option value='Indirect Coomb^s Test '>Indirect Coomb^s Test </option>
<option value='Influenza A/B (CB) '>Influenza A/B (CB) </option>
<option value='Inhibin B '>Inhibin B </option>
<option value='Insulin Abs (CB) '>Insulin Abs (CB) </option>
<option value='Insulin Growth Factor1(IGF-1) '>Insulin Growth Factor1(IGF-1) </option>
<option value='Insulin Level (1 h PP) '>Insulin Level (1 h PP) </option>
<option value='Insulin Level (2 h PP) '>Insulin Level (2 h PP) </option>
<option value='Insulin Level (Fasting) '>Insulin Level (Fasting) </option>
<option value='Insulin Like GF Binding Protein-3 (CB) '>Insulin Like GF Binding Protein-3 (CB) </option>
<option value='Insulin-Glucose T. Curve (5 samples) '>Insulin-Glucose T. Curve (5 samples) </option>
<option value='Insulin-Glucose T. Test (3 samples) '>Insulin-Glucose T. Test (3 samples) </option>
<option value='Insulin-GlucoseT. Curve (6 samples) '>Insulin-GlucoseT. Curve (6 samples) </option>
<option value='Interleukin 1- Beta (CB) '>Interleukin 1- Beta (CB) </option>
<option value='Interleukin 2 (CB) '>Interleukin 2 (CB) </option>
<option value='Interleukin 28B '>Interleukin 28B </option>
<option value='Interleukin 6 (CB) '>Interleukin 6 (CB) </option>
<option value='Inv (16) by Fish (ES) '>Inv (16) by Fish (ES) </option>
<option value='Iodine(CB) '>Iodine(CB) </option>
<option value='Ionized Calcium (Ca++). '>Ionized Calcium (Ca++). </option>
<option value='Iron in 24 hours urine '>Iron in 24 hours urine </option>
<option value='Iron Stain (Blood) '>Iron Stain (Blood) </option>
<option value='Iron Stain (BM) '>Iron Stain (BM) </option>
<option value='Irregular antibody identification (BB) '>Irregular antibody identification (BB) </option>
<option value='Itraconazole(CB) '>Itraconazole(CB) </option>
<option value='JAK 2 Mutation (V617F) '>JAK 2 Mutation (V617F) </option>
<option value='Juice Chemical examination (MX) '>Juice Chemical examination (MX) </option>
<option value='Karyotyping For Chimerism (ES) '>Karyotyping For Chimerism (ES) </option>
<option value='Karyotyping for Solid Tissue (ES) '>Karyotyping for Solid Tissue (ES) </option>
<option value='Karyotyping, High Resolution '>Karyotyping, High Resolution </option>
<option value='KJ 67 '>KJ 67 </option>
<option value='La (SS-B) '>La (SS-B) </option>
<option value='Lactate (CSF) '>Lactate (CSF) </option>
<option value='Lactic Acid '>Lactic Acid </option>
<option value='Lamotrigin (CB) '>Lamotrigin (CB) </option>
<option value='LDH '>LDH </option>
<option value='LDH in CSF '>LDH in CSF </option>
<option value='LDH Isoenzymes (CB) '>LDH Isoenzymes (CB) </option>
<option value='LDL-Cholesterol '>LDL-Cholesterol </option>
<option value='LE Cells '>LE Cells </option>
<option value='Lead In Blood (MX) '>Lead In Blood (MX) </option>
<option value='Lead in urine.(MX) '>Lead in urine.(MX) </option>
<option value='Legionella Abs (CB) '>Legionella Abs (CB) </option>
<option value='Legionella Antigen in urine (CB) '>Legionella Antigen in urine (CB) </option>
<option value='Leprosy (Microscopic Examination ) '>Leprosy (Microscopic Examination ) </option>
<option value='Leptin(CB) '>Leptin(CB) </option>
<option value='Leptospira Ab (CB) '>Leptospira Ab (CB) </option>
<option value='Leshmania Abs (CB) '>Leshmania Abs (CB) </option>
<option value='Leucine Aminopeptidase(CB) '>Leucine Aminopeptidase(CB) </option>
<option value='Levetiracetam Level in serum (CB) '>Levetiracetam Level in serum (CB) </option>
<option value='LH-RH Stimulation Test '>LH-RH Stimulation Test </option>
<option value='Lipase Level in Serum '>Lipase Level in Serum </option>
<option value='Lipoprotein Electrophoresis. '>Lipoprotein Electrophoresis. </option>
<option value='Listeria (Total antibodies) (CB) '>Listeria (Total antibodies) (CB) </option>
<option value='Lithium Level in Serum '>Lithium Level in Serum </option>
<option value='Liver autoantibody Profile '>Liver autoantibody Profile </option>
<option value='Liver Kidney Microsome ( Anti LKM) '>Liver Kidney Microsome ( Anti LKM) </option>
<option value='LKM (Titre) '>LKM (Titre) </option>
<option value='Local Fax '>Local Fax </option>
<option value='Lp(a) qualitative '>Lp(a) qualitative </option>
<option value='Lupus Anticoagulant '>Lupus Anticoagulant </option>
<option value='Luteinizing Hormone (LH) '>Luteinizing Hormone (LH) </option>
<option value='Lymph Node Culture For AFB (T.B.) '>Lymph Node Culture For AFB (T.B.) </option>
<option value='Lymph Node Film For AFB (T.B.) '>Lymph Node Film For AFB (T.B.) </option>
<option value='Lymph. Node Asp. Exam./Cult. '>Lymph. Node Asp. Exam./Cult. </option>
<option value='Lymph. Node Culture For Fungi '>Lymph. Node Culture For Fungi </option>
<option value='Lyzosyme in serum (CB) '>Lyzosyme in serum (CB) </option>
<option value='Magnesium - Erythrocytes (CB) '>Magnesium - Erythrocytes (CB) </option>
<option value='Magnesium In Urine/24 hrs '>Magnesium In Urine/24 hrs </option>
<option value='Malaria Antibodies (CB) '>Malaria Antibodies (CB) </option>
<option value='Malaria LDH Test '>Malaria LDH Test </option>
<option value='Manganese in Serum (MX) '>Manganese in Serum (MX) </option>
<option value='Measles Abs (IgG&amp;IgM) (CB) '>Measles Abs (IgG&amp;IgM) (CB) </option>
<option value='Mercury in Blood. (MX) '>Mercury in Blood. (MX) </option>
<option value='Mercury in Hair (MX) '>Mercury in Hair (MX) </option>
<option value='Metabolic Screening (FG) '>Metabolic Screening (FG) </option>
<option value='Metanephrine &amp; Normetanephrine In Urine(CB) '>Metanephrine &amp; Normetanephrine In Urine(CB) </option>
<option value='Methadone In Urine (BG) '>Methadone In Urine (BG) </option>
<option value='Methaemoglobin In Blood (CB) '>Methaemoglobin In Blood (CB) </option>
<option value='Methotrexate '>Methotrexate </option>
<option value='Methylene THF Reductase, MTHFR '>Methylene THF Reductase, MTHFR </option>
<option value='Methylmalonic Acid in serum(FG) '>Methylmalonic Acid in serum(FG) </option>
<option value='Methylmalonic acid in urine (FG) '>Methylmalonic acid in urine (FG) </option>
<option value='MFE : Food Bacteriological Examination '>MFE : Food Bacteriological Examination </option>
<option value='MFE : Hand Swab Culture...... '>MFE : Hand Swab Culture...... </option>
<option value='Microalbumin Random sample(Alb/Creat) '>Microalbumin Random sample(Alb/Creat) </option>
<option value='Microalbuminuria '>Microalbuminuria </option>
<option value='Microfilaria : Blood Film '>Microfilaria : Blood Film </option>
<option value='Monospot Test '>Monospot Test </option>
<option value='Mucopolysaccharides Screen.(BG) '>Mucopolysaccharides Screen.(BG) </option>
<option value='Mumps Abs (IgG&amp;IgM) (CB) '>Mumps Abs (IgG&amp;IgM) (CB) </option>
<option value='Mycophenolate (CB) '>Mycophenolate (CB) </option>
<option value='Mycoplasma pneumonia IgG &amp; IgM (CB) '>Mycoplasma pneumonia IgG &amp; IgM (CB) </option>
<option value='Myelin Abs(CB) '>Myelin Abs(CB) </option>
<option value='Myelin Basic Protein Abs(BG) '>Myelin Basic Protein Abs(BG) </option>
<option value='Nail Culture For Fungi '>Nail Culture For Fungi </option>
<option value='Nail Examination for Fungi '>Nail Examination for Fungi </option>
<option value='Nasal Culture For AFB (T.B.) '>Nasal Culture For AFB (T.B.) </option>
<option value='Nasal Culture For Fungi '>Nasal Culture For Fungi </option>
<option value='Nasal Discharge Film For AFB (T.B.) '>Nasal Discharge Film For AFB (T.B.) </option>
<option value='Nasal Swab Examination C/S '>Nasal Swab Examination C/S </option>
<option value='Nasopharyngeal Aspirate Exam. C/S '>Nasopharyngeal Aspirate Exam. C/S </option>
<option value='Nasopharyngeal Culture For AFB (T.B.) '>Nasopharyngeal Culture For AFB (T.B.) </option>
<option value='Nasopharyngeal Film For AFB (T.B.) '>Nasopharyngeal Film For AFB (T.B.) </option>
<option value='Natural Killer Cells (Nk) (BG) '>Natural Killer Cells (Nk) (BG) </option>
<option value='Neonatal Screening 1. (ES) '>Neonatal Screening 1. (ES) </option>
<option value='Neuromyelitis Optica Antibodies (CB) '>Neuromyelitis Optica Antibodies (CB) </option>
<option value='New test '>New test </option>
<option value='Nicotine in Urine (BG) '>Nicotine in Urine (BG) </option>
<option value='Nipple Disch. Culture For AFB (T.B.) '>Nipple Disch. Culture For AFB (T.B.) </option>
<option value='Nipple Disch. Film For AFB (T.B.) '>Nipple Disch. Film For AFB (T.B.) </option>
<option value='Nipple Discharge Exam. C/S (Left) '>Nipple Discharge Exam. C/S (Left) </option>
<option value='Nipple Discharge Exam. C/S (Right ) '>Nipple Discharge Exam. C/S (Right ) </option>
<option value='Nitro Blue Tetrazolium (N.B.T) ((AN) '>Nitro Blue Tetrazolium (N.B.T) ((AN) </option>
<option value='NSE (Neurone Specific Enolase ) (CB) '>NSE (Neurone Specific Enolase ) (CB) </option>
<option value='NSE,Cytokeratin,Chromogranin. '>NSE,Cytokeratin,Chromogranin. </option>
<option value='NTX in urine (CB) '>NTX in urine (CB) </option>
<option value='Occult Blood In Stools '>Occult Blood In Stools </option>
<option value='Occult Blood In Stools 3 Samples '>Occult Blood In Stools 3 Samples </option>
<option value='Oil,Chemical analysis (MX) '>Oil,Chemical analysis (MX) </option>
<option value='Oligoclonal Banding with index '>Oligoclonal Banding with index </option>
<option value='Opiates In Urine(Qualitative) '>Opiates In Urine(Qualitative) </option>
<option value='Opiates In Urine(Quantitative). '>Opiates In Urine(Quantitative). </option>
<option value='Opiates in blood (quantitative) (CB) '>Opiates in blood (quantitative) (CB) </option>
<option value='Organic Acids in Urine (FG) '>Organic Acids in Urine (FG) </option>
<option value='Osmatic Fragility (Fresh -Incubated) '>Osmatic Fragility (Fresh -Incubated) </option>
<option value='Osmolality in urine 24hr '>Osmolality in urine 24hr </option>
<option value='Osmolality urine random '>Osmolality urine random </option>
<option value='Osmolarity in serum (Calculated test) '>Osmolarity in serum (Calculated test) </option>
<option value='Osmotic Fragility '>Osmotic Fragility </option>
<option value='Osmotic Fragility (Incubated) '>Osmotic Fragility (Incubated) </option>
<option value='Osteocalcin (CB) '>Osteocalcin (CB) </option>
<option value='Oxalate In 24-hr Urine '>Oxalate In 24-hr Urine </option>
<option value='Panel for Immunophenotyping (DM) '>Panel for Immunophenotyping (DM) </option>
<option value='Panel reactive Antibodies (AN) '>Panel reactive Antibodies (AN) </option>
<option value='PAP Smear '>PAP Smear </option>
<option value='PAP Smear Doctor fees '>PAP Smear Doctor fees </option>
<option value='Paracetamol level (CB) '>Paracetamol level (CB) </option>
<option value='Parathyroid Hormone (PTH) '>Parathyroid Hormone (PTH) </option>
<option value='Partial Thromboplastin Time (PTT). '>Partial Thromboplastin Time (PTT). </option>
<option value='Parvo Virrus B19 by PCR (CB) '>Parvo Virrus B19 by PCR (CB) </option>
<option value='Parvo Virus B19 Ab (IgG&amp;IgM) (CB) '>Parvo Virus B19 Ab (IgG&amp;IgM) (CB) </option>
<option value='Paul Bunnel Test '>Paul Bunnel Test </option>
<option value='PCP (Phencyclidin in urine) (BG) '>PCP (Phencyclidin in urine) (BG) </option>
<option value='Pediatric urine bag '>Pediatric urine bag </option>
<option value='Perianal Swab '>Perianal Swab </option>
<option value='Pericardial Fluid Culture For AFB (T.B.) '>Pericardial Fluid Culture For AFB (T.B.) </option>
<option value='Pericardial Fluid Culture For Fungi '>Pericardial Fluid Culture For Fungi </option>
<option value='Pericardial Fluid Examination '>Pericardial Fluid Examination </option>
<option value='Pericardial Fluid Examination C/S '>Pericardial Fluid Examination C/S </option>
<option value='Pericardial Fluid Film For AFB (T.B.) '>Pericardial Fluid Film For AFB (T.B.) </option>
<option value='Peritoneal Fluid Examination '>Peritoneal Fluid Examination </option>
<option value='Peritoneal Fluid Examination C/S '>Peritoneal Fluid Examination C/S </option>
<option value='Peroxidase In Semen '>Peroxidase In Semen </option>
<option value='PH (Stool) '>PH (Stool) </option>
<option value='Phenobarbital (BG) '>Phenobarbital (BG) </option>
<option value='Phenylalanine in blood (ES) '>Phenylalanine in blood (ES) </option>
<option value='Phenytoin (Epanutin) Peak '>Phenytoin (Epanutin) Peak </option>
<option value='Phenytoin (Epanutin) Trough '>Phenytoin (Epanutin) Trough </option>
<option value='Philadelphia Chromosomes '>Philadelphia Chromosomes </option>
<option value='Phosphorus / Creatinine ratio '>Phosphorus / Creatinine ratio </option>
<option value='Phosphorus in 24-hr Urine '>Phosphorus in 24-hr Urine </option>
<option value='Phytanic acid (CB) '>Phytanic acid (CB) </option>
<option value='Pl. Aggreg. Resp. to ADP '>Pl. Aggreg. Resp. to ADP </option>
<option value='Pl. Aggreg. Resp. to Collagen '>Pl. Aggreg. Resp. to Collagen </option>
<option value='Pl. Aggreg. Resp. to Ristocetin '>Pl. Aggreg. Resp. to Ristocetin </option>
<option value='Plasma Glucose (Random) '>Plasma Glucose (Random) </option>
<option value='Plasma glucose 1h after meal '>Plasma glucose 1h after meal </option>
<option value='Plasma Glucose 1hr After 50 g Glucose... '>Plasma Glucose 1hr After 50 g Glucose... </option>
<option value='Plasma Glucose 2hrs After 75 g Glucose '>Plasma Glucose 2hrs After 75 g Glucose </option>
<option value='Plasma Glucose 2hrs PP '>Plasma Glucose 2hrs PP </option>
<option value='Plasma Metanephrine &amp; Normetanephrine '>Plasma Metanephrine &amp; Normetanephrine </option>
<option value='Plasma Renin Activity (FM) '>Plasma Renin Activity (FM) </option>
<option value='Plasminogen (CB) '>Plasminogen (CB) </option>
<option value='Platelet Antibodies (Direct ) '>Platelet Antibodies (Direct ) </option>
<option value='Platelet Count '>Platelet Count </option>
<option value='Platelet rich plasma (PRP) '>Platelet rich plasma (PRP) </option>
<option value='Platelets Antibodies (Indirect ) '>Platelets Antibodies (Indirect ) </option>
<option value='Pleural Fluid Culture For AFB (T.B.) '>Pleural Fluid Culture For AFB (T.B.) </option>
<option value='Pleural Fluid Culture For Fungi '>Pleural Fluid Culture For Fungi </option>
<option value='Pleural Fluid Examination C/S '>Pleural Fluid Examination C/S </option>
<option value='Pleural Fluid Examination... '>Pleural Fluid Examination... </option>
<option value='Pleural Fluid Film For AFB (T.B.) '>Pleural Fluid Film For AFB (T.B.) </option>
<option value='Pleural fluid for T.B by PCR '>Pleural fluid for T.B by PCR </option>
<option value='Porphobilinogen in Urine (BG) '>Porphobilinogen in Urine (BG) </option>
<option value='Post Coital Test '>Post Coital Test </option>
<option value='Potassium - Creatinine Ratio '>Potassium - Creatinine Ratio </option>
<option value='Pre albumin (CB) '>Pre albumin (CB) </option>
<option value='Pregnancy Associated Plasma Protein A (BG) '>Pregnancy Associated Plasma Protein A (BG) </option>
<option value='Pregnandiol(CB) '>Pregnandiol(CB) </option>
<option value='Procalcitonin (PCT)(wn) '>Procalcitonin (PCT)(wn) </option>
<option value='Procollagen III (CB) '>Procollagen III (CB) </option>
<option value='Progesterone '>Progesterone </option>
<option value='Progesterone Receptors (Breast). '>Progesterone Receptors (Breast). </option>
<option value='Proinsulin (CB) '>Proinsulin (CB) </option>
<option value='Prolactin (PRL). '>Prolactin (PRL). </option>
<option value='Prostatic Discharge Culture For AFB (T.B.) '>Prostatic Discharge Culture For AFB (T.B.) </option>
<option value='Prostatic Discharge Culture For Fungi '>Prostatic Discharge Culture For Fungi </option>
<option value='Prostatic Discharge Film For AFB (T.B.) '>Prostatic Discharge Film For AFB (T.B.) </option>
<option value='Prostatic Fl. Exam. C/S '>Prostatic Fl. Exam. C/S </option>
<option value='Prostatic Fluid Examination '>Prostatic Fluid Examination </option>
<option value='Prostatic Specific Antigen (Free PSA). '>Prostatic Specific Antigen (Free PSA). </option>
<option value='Prostatic Specific Antigen (Total PSA) '>Prostatic Specific Antigen (Total PSA) </option>
<option value='Protein Bound Iodine (PBI) '>Protein Bound Iodine (PBI) </option>
<option value='Protein C Activity '>Protein C Activity </option>
<option value='Protein electrophoresis in urine (AN) '>Protein electrophoresis in urine (AN) </option>
<option value='Protein in CSF '>Protein in CSF </option>
<option value='Protein S Level '>Protein S Level </option>
<option value='Protein-Creatinine Ratio in Urine '>Protein-Creatinine Ratio in Urine </option>
<option value='Proteins in 24hrs urine '>Proteins in 24hrs urine </option>
<option value='Prothrombin 20210 '>Prothrombin 20210 </option>
<option value='Prothrombin Time &amp; Conc... '>Prothrombin Time &amp; Conc... </option>
<option value='PSA (Total &amp; Free) '>PSA (Total &amp; Free) </option>
<option value='Pus Culture For AFB (T.B.) '>Pus Culture For AFB (T.B.) </option>
<option value='Pus Culture For Fungi '>Pus Culture For Fungi </option>
<option value='Pus Examination &amp; C/S '>Pus Examination &amp; C/S </option>
<option value='Pus Film For AFB (T.B.) '>Pus Film For AFB (T.B.) </option>
<option value='Pyruvate in CSF (CB) '>Pyruvate in CSF (CB) </option>
<option value='Pyruvate in Whole Blood '>Pyruvate in Whole Blood </option>
<option value='Pyruvate Kinase (PK) ((CB) '>Pyruvate Kinase (PK) ((CB) </option>
<option value='Quantiferon_TB Gold In _Tube '>Quantiferon_TB Gold In _Tube </option>
<option value='Rapid Plasma Reagin (RPR) '>Rapid Plasma Reagin (RPR) </option>
<option value='RARA gene by fish (ES) '>RARA gene by fish (ES) </option>
<option value='RARA gene by PCR (ES) '>RARA gene by PCR (ES) </option>
<option value='Rast 1 (Specific IgE). '>Rast 1 (Specific IgE). </option>
<option value='Rast 2 (Specific IgE). '>Rast 2 (Specific IgE). </option>
<option value='Rast-Specific IgE (Chocolate) '>Rast-Specific IgE (Chocolate) </option>
<option value='Rast-Specific IgE (Cow milk) '>Rast-Specific IgE (Cow milk) </option>
<option value='Rast-Specific IgE (Fusarium) '>Rast-Specific IgE (Fusarium) </option>
<option value='Rast-Specific IgE (Honey Bee) '>Rast-Specific IgE (Honey Bee) </option>
<option value='Rast-Specific IgE (Moulds I) '>Rast-Specific IgE (Moulds I) </option>
<option value='Rast-Specific IgE (Moulds II) '>Rast-Specific IgE (Moulds II) </option>
<option value='Rast-Specific IgE (Peanut) '>Rast-Specific IgE (Peanut) </option>
<option value='Rast-Specific IgE (Strawberry) '>Rast-Specific IgE (Strawberry) </option>
<option value='Rast-Specific IgE (Yeast ) '>Rast-Specific IgE (Yeast ) </option>
<option value='Rast-Specific IgE (Alternaia) '>Rast-Specific IgE (Alternaia) </option>
<option value='Rast-Specific IgE (Aspergillus) '>Rast-Specific IgE (Aspergillus) </option>
<option value='Rast-Specific IgE (Candida) '>Rast-Specific IgE (Candida) </option>
<option value='Rast-Specific IgE (Casein) '>Rast-Specific IgE (Casein) </option>
<option value='Rast-Specific IgE (Cat) '>Rast-Specific IgE (Cat) </option>
<option value='Rast-Specific IgE (Egg) '>Rast-Specific IgE (Egg) </option>
<option value='Rast-Specific IgE (Fish) '>Rast-Specific IgE (Fish) </option>
<option value='Rast-Specific IgE (Glutin) '>Rast-Specific IgE (Glutin) </option>
<option value='Rast-Specific IgE (Helminthosporium) '>Rast-Specific IgE (Helminthosporium) </option>
<option value='Rast-Specific IgE (Milk) '>Rast-Specific IgE (Milk) </option>
<option value='Rast-Specific IgE (Mite - Farinae) '>Rast-Specific IgE (Mite - Farinae) </option>
<option value='Rast-Specific IgE (Mite - Pteronyss) '>Rast-Specific IgE (Mite - Pteronyss) </option>
<option value='Rast-Specific IgE (Nuts) '>Rast-Specific IgE (Nuts) </option>
<option value='Rast-Specific IgE (Pulluaria) '>Rast-Specific IgE (Pulluaria) </option>
<option value='Rast-Specific IgE (Soybean) '>Rast-Specific IgE (Soybean) </option>
<option value='Rast-Specific IgE (Storage Mite) '>Rast-Specific IgE (Storage Mite) </option>
<option value='Rast-Specific IgE (Wheat) '>Rast-Specific IgE (Wheat) </option>
<option value='RBCs Count '>RBCs Count </option>
<option value='Ready to eat food '>Ready to eat food </option>
<option value='Reducing Sugar in Urine '>Reducing Sugar in Urine </option>
<option value='Respiratory Syncitial Virurs -RSV (CB) '>Respiratory Syncitial Virurs -RSV (CB) </option>
<option value='Respiratory syncytial virus Abs (CB) '>Respiratory syncytial virus Abs (CB) </option>
<option value='Result Retyping '>Result Retyping </option>
<option value='Result Retyping DNA '>Result Retyping DNA </option>
<option value='Reticulocyte Count '>Reticulocyte Count </option>
<option value='Rh Genotyping (BG) '>Rh Genotyping (BG) </option>
<option value='Rh group. '>Rh group. </option>
<option value='Rh(Du) . '>Rh(Du) . </option>
<option value='Rheumatoid factor (IgA) (CB) '>Rheumatoid factor (IgA) (CB) </option>
<option value='Rheumatoid Factor (Latex &amp; Rose- Waaler) '>Rheumatoid Factor (Latex &amp; Rose- Waaler) </option>
<option value='Rheumatoid Factor (Rose-Waaler). '>Rheumatoid Factor (Rose-Waaler). </option>
<option value='Rheumatoid Factor Titre '>Rheumatoid Factor Titre </option>
<option value='RIBA Test For HCV(AN) '>RIBA Test For HCV(AN) </option>
<option value='Ring Worm Examination '>Ring Worm Examination </option>
<option value='Rivotril (Clonazepam)(CB) '>Rivotril (Clonazepam)(CB) </option>
<option value='Ro (SS-A). '>Ro (SS-A). </option>
<option value='Rotavirus Antigen '>Rotavirus Antigen </option>
<option value='Rubella Antibodies (IgG) '>Rubella Antibodies (IgG) </option>
<option value='Rubella Antibodies (IgM) '>Rubella Antibodies (IgM) </option>
<option value='Sacchromyces Cerevisiae ABS (ASCA) '>Sacchromyces Cerevisiae ABS (ASCA) </option>
<option value='Salicylate, Qualitative(CB) '>Salicylate, Qualitative(CB) </option>
<option value='Salmonella &amp; Shigella Spp. (Stool) '>Salmonella &amp; Shigella Spp. (Stool) </option>
<option value='Schebo Test.... '>Schebo Test.... </option>
<option value='SCL70 Ab Quant (AN) '>SCL70 Ab Quant (AN) </option>
<option value='Screening For Drugs of Abuse '>Screening For Drugs of Abuse </option>
<option value='Selenium in Serum (MX) '>Selenium in Serum (MX) </option>
<option value='Semen Culture For AFB (T.B.) '>Semen Culture For AFB (T.B.) </option>
<option value='Semen Culture For Fungi '>Semen Culture For Fungi </option>
<option value='Semen Examination '>Semen Examination </option>
<option value='Semen Examination &amp; C/S '>Semen Examination &amp; C/S </option>
<option value='Semen Film For AFB (T.B.) '>Semen Film For AFB (T.B.) </option>
<option value='Semen Processing '>Semen Processing </option>
<option value='Sensitivity Food '>Sensitivity Food </option>
<option value='Serology For Brucella '>Serology For Brucella </option>
<option value='Serotonin in Blood (CB) '>Serotonin in Blood (CB) </option>
<option value='Serotonin in urine '>Serotonin in urine </option>
<option value='Serum Urea '>Serum Urea </option>
<option value='Serum Albumin '>Serum Albumin </option>
<option value='Serum Aldolase '>Serum Aldolase </option>
<option value='Serum Amylase '>Serum Amylase </option>
<option value='Serum Anti Sperm Antibodies (Titre) '>Serum Anti Sperm Antibodies (Titre) </option>
<option value='Serum Bicarbonates. '>Serum Bicarbonates. </option>
<option value='Serum Calcium (Total). '>Serum Calcium (Total). </option>
<option value='Serum Cannabis Confirmation Test (CB) '>Serum Cannabis Confirmation Test (CB) </option>
<option value='Serum Chloride '>Serum Chloride </option>
<option value='Serum Cholesterol '>Serum Cholesterol </option>
<option value='Serum Cortisol 5 pm '>Serum Cortisol 5 pm </option>
<option value='Serum Cortisol 9 am '>Serum Cortisol 9 am </option>
<option value='Serum Cortisol 9 pm '>Serum Cortisol 9 pm </option>
<option value='Serum Creatinine '>Serum Creatinine </option>
<option value='Serum DHEA (BG) '>Serum DHEA (BG) </option>
<option value='Serum DHEA-S '>Serum DHEA-S </option>
<option value='Serum Globulin '>Serum Globulin </option>
<option value='Serum Immunofixation '>Serum Immunofixation </option>
<option value='Serum Iron Level '>Serum Iron Level </option>
<option value='Serum Magnesium. '>Serum Magnesium. </option>
<option value='Serum Myeloperoxidase Abs '>Serum Myeloperoxidase Abs </option>
<option value='Serum Myoglobin '>Serum Myoglobin </option>
<option value='Serum Osmolality '>Serum Osmolality </option>
<option value='Serum Phosphorus '>Serum Phosphorus </option>
<option value='Serum Potassium (K) '>Serum Potassium (K) </option>
<option value='Serum Protein Electrophoresis '>Serum Protein Electrophoresis </option>
<option value='Serum Sodium (Na) '>Serum Sodium (Na) </option>
<option value='Serum Sodium and Potassium '>Serum Sodium and Potassium </option>
<option value='Serum Thyroglobulin Level '>Serum Thyroglobulin Level </option>
<option value='Serum Total Protein '>Serum Total Protein </option>
<option value='Serum Uric Acid '>Serum Uric Acid </option>
<option value='Sex Hormone Binding Globulin (SHBG) '>Sex Hormone Binding Globulin (SHBG) </option>
<option value='SGOT (AST) '>SGOT (AST) </option>
<option value='SGPT (ALT) '>SGPT (ALT) </option>
<option value='Siblingship DNA Testing. (ES) '>Siblingship DNA Testing. (ES) </option>
<option value='Sickling test '>Sickling test </option>
<option value='Silt density index (S.D.I) (mx) '>Silt density index (S.D.I) (mx) </option>
<option value='Sirolimus '>Sirolimus </option>
<option value='Skin Culture for fungi..... '>Skin Culture for fungi..... </option>
<option value='Skin Examination For Fungi '>Skin Examination For Fungi </option>
<option value='Skin IF Tests : C3 '>Skin IF Tests : C3 </option>
<option value='Skin IF Tests : IgA '>Skin IF Tests : IgA </option>
<option value='Skin IF Tests : IgG '>Skin IF Tests : IgG </option>
<option value='Skin IF Tests : IgG/A/M &amp; C3 '>Skin IF Tests : IgG/A/M &amp; C3 </option>
<option value='Skin IF Tests : IgM '>Skin IF Tests : IgM </option>
<option value='Skin Prick Test. '>Skin Prick Test. </option>
<option value='SMS '>SMS </option>
<option value='Special Cultures : Campylobacter spp. '>Special Cultures : Campylobacter spp. </option>
<option value='Special Cultures : Listeria Spp (Vag.)(BG) '>Special Cultures : Listeria Spp (Vag.)(BG) </option>
<option value='Special Cultures : Mycoplasma Hominis '>Special Cultures : Mycoplasma Hominis </option>
<option value='Special Cultures : Neisseria Gonorrhea '>Special Cultures : Neisseria Gonorrhea </option>
<option value='Special Cultures : Salmonella Spp. (Blood) '>Special Cultures : Salmonella Spp. (Blood) </option>
<option value='Special Cultures : Salmonella Spp. (Stool) '>Special Cultures : Salmonella Spp. (Stool) </option>
<option value='Special Cultures : Shigella Spp. '>Special Cultures : Shigella Spp. </option>
<option value='Special Cultures : Shigella Spp. (Stool) '>Special Cultures : Shigella Spp. (Stool) </option>
<option value='Special Cultures : Ureaplasma '>Special Cultures : Ureaplasma </option>
<option value='Special Cultures : Ureaplasma Urealyticum '>Special Cultures : Ureaplasma Urealyticum </option>
<option value='Special Staining '>Special Staining </option>
<option value='Special Test for MRSA '>Special Test for MRSA </option>
<option value='Specific (IgE) Allergens (MIX) '>Specific (IgE) Allergens (MIX) </option>
<option value='Spinal Musculer Atrophy (CB) '>Spinal Musculer Atrophy (CB) </option>
<option value='Spirometric Lung Function '>Spirometric Lung Function </option>
<option value='Sputum Culture For AFB (T.B.) 3 Samples '>Sputum Culture For AFB (T.B.) 3 Samples </option>
<option value='Sputum Culture For Fungi '>Sputum Culture For Fungi </option>
<option value='Sputum Examination C/S '>Sputum Examination C/S </option>
<option value='Sputum Examination for fungi '>Sputum Examination for fungi </option>
<option value='Sputum Film For AFB (1 Sample) '>Sputum Film For AFB (1 Sample) </option>
<option value='Sputum Film For AFB (3 Samples) '>Sputum Film For AFB (3 Samples) </option>
<option value='Sputum Film For AFB (5 Samples) '>Sputum Film For AFB (5 Samples) </option>
<option value='Squamous Cell Carcinoma(SCC) (CB) '>Squamous Cell Carcinoma(SCC) (CB) </option>
<option value='Stamey.s Test (Meares &amp; Stamey) '>Stamey.s Test (Meares &amp; Stamey) </option>
<option value='Stillbirth (Autopsy) '>Stillbirth (Autopsy) </option>
<option value='Stone Analysis '>Stone Analysis </option>
<option value='Stool Culture For AFB (T.B.) 3 Samples '>Stool Culture For AFB (T.B.) 3 Samples </option>
<option value='Stool Culture For Fungi '>Stool Culture For Fungi </option>
<option value='Stool Examination '>Stool Examination </option>
<option value='Stool Examination C/S '>Stool Examination C/S </option>
<option value='Stool Film For AFB (T.B.) '>Stool Film For AFB (T.B.) </option>
<option value='Stool For Bilharzia (Quantitative) '>Stool For Bilharzia (Quantitative) </option>
<option value='Stool For Reducing Sugars '>Stool For Reducing Sugars </option>
<option value='Streptococci group B (S.agalactiea) '>Streptococci group B (S.agalactiea) </option>
<option value='Succinylacetone in blood (FG) '>Succinylacetone in blood (FG) </option>
<option value='Succinylacetone in urine (FG) '>Succinylacetone in urine (FG) </option>
<option value='Sucrose Lysis Test '>Sucrose Lysis Test </option>
<option value='Sulpher (MX) '>Sulpher (MX) </option>
<option value='Superoxide Dismutase (CB) '>Superoxide Dismutase (CB) </option>
<option value='Surface Immunoglobulin (SIG) '>Surface Immunoglobulin (SIG) </option>
<option value='Sweat Chloride Test '>Sweat Chloride Test </option>
<option value='Synovial Fluid Culture For AFB (T.B.) '>Synovial Fluid Culture For AFB (T.B.) </option>
<option value='Synovial Fluid Culture For Fungi '>Synovial Fluid Culture For Fungi </option>
<option value='Synovial Fluid Examination '>Synovial Fluid Examination </option>
<option value='Synovial Fluid Examination &amp; C/S '>Synovial Fluid Examination &amp; C/S </option>
<option value='Synovial Fluid Film For AFB (T.B.) '>Synovial Fluid Film For AFB (T.B.) </option>
<option value='T.B. DNA by PCR (Ascitic Fluid) '>T.B. DNA by PCR (Ascitic Fluid) </option>
<option value='T.B. DNA by PCR (Blood) '>T.B. DNA by PCR (Blood) </option>
<option value='T.B. DNA by PCR (Pleural Fluid) '>T.B. DNA by PCR (Pleural Fluid) </option>
<option value='T.B. DNA by PCR (Sputum) '>T.B. DNA by PCR (Sputum) </option>
<option value='T.B. DNA by PCR (Urine) '>T.B. DNA by PCR (Urine) </option>
<option value='T.B. in Biological fluid by PCR '>T.B. in Biological fluid by PCR </option>
<option value='T3 '>T3 </option>
<option value='T3 Uptake '>T3 Uptake </option>
<option value='T4 '>T4 </option>
<option value='Tacrolimus (FK 506) '>Tacrolimus (FK 506) </option>
<option value='T-Cell Receptor (TCR) (BG) '>T-Cell Receptor (TCR) (BG) </option>
<option value='Tegretol (Carbamazepine) Peak '>Tegretol (Carbamazepine) Peak </option>
<option value='Tegretol (Carbamazepine), Trough '>Tegretol (Carbamazepine), Trough </option>
<option value='Testicular Biopsy '>Testicular Biopsy </option>
<option value='Testosterone '>Testosterone </option>
<option value='Tetanus Abs(CB) '>Tetanus Abs(CB) </option>
<option value='Thalasemia gene (Alpha) (ES) '>Thalasemia gene (Alpha) (ES) </option>
<option value='Thalasemia gene (Beta) (ES) '>Thalasemia gene (Beta) (ES) </option>
<option value='Theophylline Level '>Theophylline Level </option>
<option value='Thiopurine-S-Methyltransferase (CIC) '>Thiopurine-S-Methyltransferase (CIC) </option>
<option value='Throat Swab Culture For Fungi '>Throat Swab Culture For Fungi </option>
<option value='Throat Swab Examination &amp; C/S '>Throat Swab Examination &amp; C/S </option>
<option value='Thrombin Time '>Thrombin Time </option>
<option value='Thyroxine Binding Globulin (CB) '>Thyroxine Binding Globulin (CB) </option>
<option value='Tissue biopsy culture and sensitivity '>Tissue biopsy culture and sensitivity </option>
<option value='Topiramate (LC-MS/MS) XXX (CB) '>Topiramate (LC-MS/MS) XXX (CB) </option>
<option value='TORCH (IgG) (Toxo/Rub/CMV/HSV 1&amp;2) '>TORCH (IgG) (Toxo/Rub/CMV/HSV 1&amp;2) </option>
<option value='TORCH (IgM) (Toxo/Rub/CMV/HSV 1&amp;2) '>TORCH (IgM) (Toxo/Rub/CMV/HSV 1&amp;2) </option>
<option value='Total &amp; Ionized Calcium (Ca++). '>Total &amp; Ionized Calcium (Ca++). </option>
<option value='Total Iron Binding capacity (TIBC) '>Total Iron Binding capacity (TIBC) </option>
<option value='Total Leucocytic Count '>Total Leucocytic Count </option>
<option value='Total Leucocytic count / Hb. &amp; Ht. '>Total Leucocytic count / Hb. &amp; Ht. </option>
<option value='Total Lipids '>Total Lipids </option>
<option value='Total organic carbon (MX) '>Total organic carbon (MX) </option>
<option value='Toxocara Abs (CB) '>Toxocara Abs (CB) </option>
<option value='Toxoplama IgG Avidity Test (CB) '>Toxoplama IgG Avidity Test (CB) </option>
<option value='Toxoplasma Antibodies (IgG) '>Toxoplasma Antibodies (IgG) </option>
<option value='Toxoplasma Antibodies (IgM) '>Toxoplasma Antibodies (IgM) </option>
<option value='Toxoplasmosis DNA by PCR (CB) '>Toxoplasmosis DNA by PCR (CB) </option>
<option value='Tramadol in urine.... '>Tramadol in urine.... </option>
<option value='Transferrin Level In Serum '>Transferrin Level In Serum </option>
<option value='Transferrin Saturation '>Transferrin Saturation </option>
<option value='Translocation 15,17 by FISH (ES) '>Translocation 15,17 by FISH (ES) </option>
<option value='Trichinella Serology (CB) '>Trichinella Serology (CB) </option>
<option value='Trichinosis Abs (CB) '>Trichinosis Abs (CB) </option>
<option value='Triglycerides '>Triglycerides </option>
<option value='Triple Marker Test '>Triple Marker Test </option>
<option value='Trisomy 12 by FISH (ES) '>Trisomy 12 by FISH (ES) </option>
<option value='Troponin I (quantitative). '>Troponin I (quantitative). </option>
<option value='Tryptase (CB) '>Tryptase (CB) </option>
<option value='TSH '>TSH </option>
<option value='TSH receptors ABS (BL) '>TSH receptors ABS (BL) </option>
<option value='Tuberculin Test '>Tuberculin Test </option>
<option value='Tumor Marker: CA 125 '>Tumor Marker: CA 125 </option>
<option value='Tumor Marker: CA 15-3 '>Tumor Marker: CA 15-3 </option>
<option value='Tumor Marker: CA 19-9 '>Tumor Marker: CA 19-9 </option>
<option value='Tumor Necrosis Factor, Alpha(CB) '>Tumor Necrosis Factor, Alpha(CB) </option>
<option value='Ulcer Film For AFB (T.B.) '>Ulcer Film For AFB (T.B.) </option>
<option value='Ulcer Culture For AFB (T.B.) '>Ulcer Culture For AFB (T.B.) </option>
<option value='Ulcer Culture For Fungi '>Ulcer Culture For Fungi </option>
<option value='Ulcer Swab Examination &amp; Culture '>Ulcer Swab Examination &amp; Culture </option>
<option value='Unstable Haemoglobin (AN) '>Unstable Haemoglobin (AN) </option>
<option value='Urea Clearance '>Urea Clearance </option>
<option value='Urethral Culture For Fungi '>Urethral Culture For Fungi </option>
<option value='Urethral Discharge Examination and C/S '>Urethral Discharge Examination and C/S </option>
<option value='Uric Acid / Creatinine '>Uric Acid / Creatinine </option>
<option value='Urinary Bladder Cancer (UBC)Detection '>Urinary Bladder Cancer (UBC)Detection </option>
<option value='Urinary Porphyrins.(BG) '>Urinary Porphyrins.(BG) </option>
<option value='Urinary Potassium / 24hrs '>Urinary Potassium / 24hrs </option>
<option value='Urinary Pregnanetriol (CB) '>Urinary Pregnanetriol (CB) </option>
<option value='Urinary Sodium / 24hrs '>Urinary Sodium / 24hrs </option>
<option value='Urine Culture For Fungi '>Urine Culture For Fungi </option>
<option value='Urine Analysis '>Urine Analysis </option>
<option value='Urine Analysis &amp; C/S '>Urine Analysis &amp; C/S </option>
<option value='Urine Chloride '>Urine Chloride </option>
<option value='Urine Culture For AFB (T.B.) 3 Samples '>Urine Culture For AFB (T.B.) 3 Samples </option>
<option value='Urine Culture For AFB (T.B.), 3 Samples '>Urine Culture For AFB (T.B.), 3 Samples </option>
<option value='Urine Examination (24 hours) '>Urine Examination (24 hours) </option>
<option value='Urine Film For AFB (3 Samples) '>Urine Film For AFB (3 Samples) </option>
<option value='Urine Film For AFB (one Sample) '>Urine Film For AFB (one Sample) </option>
<option value='Urine Film For AFB(5 Samples) '>Urine Film For AFB(5 Samples) </option>
<option value='Urine For Acetone '>Urine For Acetone </option>
<option value='Urine For Bilharzia (Quantitative) '>Urine For Bilharzia (Quantitative) </option>
<option value='Urine For Glucose &amp; Acetone '>Urine For Glucose &amp; Acetone </option>
<option value='Urine for Gram Stain '>Urine for Gram Stain </option>
<option value='Urine Specific Gravity '>Urine Specific Gravity </option>
<option value='Urine Uric Acid / 24hrs '>Urine Uric Acid / 24hrs </option>
<option value='Urobilinogen In Urine '>Urobilinogen In Urine </option>
<option value='Vaccine Set. '>Vaccine Set. </option>
<option value='Vaginal Culture For Fungi '>Vaginal Culture For Fungi </option>
<option value='Vaginal des. Doctor fees '>Vaginal des. Doctor fees </option>
<option value='Vaginal Discharge Exam. &amp; C/S '>Vaginal Discharge Exam. &amp; C/S </option>
<option value='Vaginal Film For Monilia '>Vaginal Film For Monilia </option>
<option value='Valval Culture For Fungi '>Valval Culture For Fungi </option>
<option value='Vancomycin (BL) '>Vancomycin (BL) </option>
<option value='Vanilmandelic Acid in Urine (VMA) '>Vanilmandelic Acid in Urine (VMA) </option>
<option value='Varicella Zoster Antibodies IgM &amp; IgG '>Varicella Zoster Antibodies IgM &amp; IgG </option>
<option value='Varicella Zoster Virus DNA (CB) '>Varicella Zoster Virus DNA (CB) </option>
<option value='Vaso-Intestinal Polypeptide- VIP (CB) '>Vaso-Intestinal Polypeptide- VIP (CB) </option>
<option value='VDRL '>VDRL </option>
<option value='Very long chain Fatty Acids (FG) '>Very long chain Fatty Acids (FG) </option>
<option value='Vitamin A (Retinol) (CB) '>Vitamin A (Retinol) (CB) </option>
<option value='Vitamin B1 (CB) '>Vitamin B1 (CB) </option>
<option value='Vitamin B12 (cyanocobalamine)... '>Vitamin B12 (cyanocobalamine)... </option>
<option value='Vitamin B2 (CB) '>Vitamin B2 (CB) </option>
<option value='Vitamin B6 (CB) '>Vitamin B6 (CB) </option>
<option value='Vitamin C (CB) '>Vitamin C (CB) </option>
<option value='Vitamin D (1,25 Dihydroxy) (CB) '>Vitamin D (1,25 Dihydroxy) (CB) </option>
<option value='Vitamin E (Alpha Tocopherol) (CB) '>Vitamin E (Alpha Tocopherol) (CB) </option>
<option value='Vitamin K (Phylloquinone (CB) '>Vitamin K (Phylloquinone (CB) </option>
<option value='VLDL- Cholesterol '>VLDL- Cholesterol </option>
<option value='Von Willebrand Factor (DM) '>Von Willebrand Factor (DM) </option>
<option value='Vulval Swab Exam. &amp; C/S '>Vulval Swab Exam. &amp; C/S </option>
<option value='Waste water examination (MX) '>Waste water examination (MX) </option>
<option value='Water : Bacteriological Assessment '>Water : Bacteriological Assessment </option>
<option value='Water : Chemical Analysis. (MX) '>Water : Chemical Analysis. (MX) </option>
<option value='Water :Biochemical Oxygen Demand(MX) '>Water :Biochemical Oxygen Demand(MX) </option>
<option value='Water analysis : Total Suspended Solids (MX) '>Water analysis : Total Suspended Solids (MX) </option>
<option value='Water examination : Mercury (MX) '>Water examination : Mercury (MX) </option>
<option value='Wax block '>Wax block </option>
<option value='WBC count : Total &amp; Differential '>WBC count : Total &amp; Differential </option>
<option value='WDT '>WDT </option>
<option value='Western Blot For HIV (BG) '>Western Blot For HIV (BG) </option>
<option value='Widal &amp; Brucella Test. '>Widal &amp; Brucella Test. </option>
<option value='Widal Test.'>Widal Test. </option>
<option value='X - Y chromosome by Fish (ES) '>X - Y chromosome by Fish (ES) </option>
<option value='Y-chromosomal deletion by PCR (BL) '>Y-chromosomal deletion by PCR (BL) </option>
<option value='Yellow Fever (CB) '>Yellow Fever (CB) </option>
<option value='Yersinia serology (CB) '>Yersinia serology (CB) </option>
<option value='ZAP 70 '>ZAP 70 </option>
<option value='Zarontin (Ethosuximide) Level (CB) '>Zarontin (Ethosuximide) Level (CB) </option>
<option value='Zinc In Blood. '>Zinc In Blood. </option>
<option value='Zinc in hair (MX) '>Zinc in hair (MX) </option>
<option value='Zinc in Milk (MX) '>Zinc in Milk (MX) </option>
<option value='Zinc In Urine '>Zinc In Urine </option>



                        </select>
                        <label for="floatingSelectGrid">Analysis name</label>
                    </div>
                    </div>